### ISSUE TITLE
Provide popover on home screen card to define "landscape" concept for first time user

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1004]
On the home screen provide a popover introducing the concept of a landscape to the first-time user:

<img width="591" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/a7edd0bc-d9d6-4f9e-a87f-32734c6115a1">

**popover open**
Copy: `A landscape is a territory defined by natural or administrative boundaries, in which people and nature live together. It is influenced by ecological, historical, economic, and socio-cultural processes and activities that take place within and adjacent to the region.`
MUI: https://mui.com/material-ui/react-popover/
<img width="610" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/32e3cdfe-d79c-4413-af11-f190403f24f4">

### Product
- [ ] As a user looking at the landscapes card, I should be able to understand the concept of a landscape so that I know what I will be observing in the landscapes directory

### Design
- [x] Copy Edited
- [ ] Implemented as designed
- [ ] Translated

**Comment by jodiezhuu** [comment]
@Hanal-code @DerekCaelin Do we only want this popover in the default landscape home card? Or even after landscapes have been added

**Comment by DerekCaelin** [comment]
Hi @jodiezhuu It should persist.

**Comment by Hanal-code** [comment]
@jodiezhuu FYI: The same popover pattern has been used in the new landscape form. Either you can use the same component or iterate it  --  spacing between the close button and the content needs to be 8px or more (depending on the line length).   https://app.staging.terraso.net/landscapes/new

**Comment by jodiezhuu** [comment]
Thanks @Hanal-code ! That's very helpful

**Comment by jodiezhuu** [comment]
@Hanal-code @DerekCaelin Just to confirm, no Spanish translations yet, correct?

**Comment by DerekCaelin** [comment]
@jodiezhuu Once English is complete, please assign the task to @josebui for translation to spanish.
