### ISSUE TITLE
Add caption to home screen story map thumbnail according to design:

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1005]
Add caption to story map image on home screen for user without story maps:
app.staging.terraso.net 

![Image](https://github.com/techmatters/terraso-web-client/assets/10799815/f632a611-a6f3-45fb-aeb3-9b706acc41a0)

**Comment by paulschreiber** [comment]
@DerekCaelin That looks too small to read. Can we add it as alt text instead?

**Comment by DerekCaelin** [comment]
I have no issue with that proposal - @Hanal-code, this is emerging from your design, what do you think?

**Comment by Hanal-code** [comment]
@DerekCaelin @paulschreiber Please add the story map name as a visible caption and the Alt text.

**Comment by paulschreiber** [comment]
If we do both, we should mark the visible caption as `aria-hidden`.

**Comment by DerekCaelin** [comment]
@Hanal-code what do you think of that?

**Comment by Hanal-code** [comment]
@DerekCaelin yes, that makes sense.
