### ISSUE TITLE
email for authorizing request to join closed group contains old colors and branding

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1018]
## Description
When users request to join a new project. 

Related issue: https://github.com/techmatters/terraso-web-client/issues/653

## Steps To Reproduce
1. Go to groups screen: https://app.terraso.org/groups
2. request to join a closed group
3. be manager of closed group, check received email

## Expected behavior
Terraso email should have current Terraso branding.
![Terraso-logo-V2-wTM](https://github.com/techmatters/terraso-web-client/assets/10799815/93f8026e-d81b-4923-89d7-69137fd7139c)

## Actual behavior
<img width="700" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/2a0b993c-a46b-4221-8ad0-84370d5290af">

**Comment by paulschreiber** [comment]
Turns out this had already
