### ISSUE TITLE
error message when adding a >200 character link description to shared files module is not human readable

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1080]
## Description
When sharing a link in a shared files module and providing a greater-than 200 character description, the error message that appears is not human readable

## Steps To Reproduce

1. Be a member of a group/landscape
2. share a url in the shared files module
3. include a description of the file that is greater than 200 characters, eg: `Our first gathering in a loop around the town. We learned about safety in riding as a group - how to communicate, what signals to use. We also saw how our town will benefit from more biking infrastructure by allowing even more people to get around by bike.`
5. See error

## Expected behavior
A human readable error with description on how to address the problem, eg, `The description is too long. Please add a description that is fewer than 200 characters.`

## Actual behavior
Error message: `sharedData.upload_link_form.description must be fewer than 200 characters.`
<img width="1214" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/26fbc778-4891-4b33-abbf-ee65d6d0e436">
\

**Comment by paulschreiber** [comment]
"is not human-readable" is not accurate. The problem is that the string was not localized.
