### ISSUE TITLE
Update the drag icon in Data map

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#1109]
## Description
The icon got updated unknowingly. Swap the current one to the attached SVG (![DragCustom](https://github.com/techmatters/terraso-web-client/assets/92342777/e39f92ce-f88f-43ba-8e92-f55b85a5a727))

## Steps To Reproduce

1. Go to URL: https://app.terraso.org/groups/data-viz-community-of-practice/map/new OR any group/landscape with data map. 
2. Note the drag icon has changed

<img width="736" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/b41c87c1-5b2b-400e-8c83-69dc63169764">

## Expected behavior

<img width="193" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/26885b71-aa72-4ee7-bb28-c0f348cfaa1e">

## Actual behavior
See the above

**Comment by paulschreiber** [comment]
This is the correct Material UI drag handle. I reviewed both the library code, and it does not appear to have changed since 2021.
