### ISSUE TITLE
Old branding appears in the Terraso login screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1126]
## Description
When logging in to Terraso with a google account, the old branding is still visible. 

## Steps To Reproduce
1. Open an incognito window.
2. Go to app.terraso.org
3. Log in with google
4. See issue

## Expected behavior
See updated branding

## Actual behavior
Old colors are visible.
<img width="500" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/7b983d28-43d9-464f-a11a-1d0b58d8c2fb">

## Additional context
Apparently this requires a human to review in Google.

**Comment by paulschreiber** [comment]
This was submitted May 8. Review has been requested from Google.
