### ISSUE TITLE
Form validation: allow URLs without protocol

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#115]
## Description
Currently, we accept `https://www.example.com` but not `www.example.com`.

We should accept both, and automatically add the URL scheme if the user omits it.

**Comment by ssfrancis** [comment]
How will we know if it should be http:// or https://?  Can we / will we test programmatically?

**Comment by paulschreiber** [comment]
99% of sites are https. If someone needs `http`, they will have to enter it manually.

**Comment by Hanal-code** [comment]
Change the input field not to require the users to enter 'http://www...' The web address bar starts with the name nowadays.  e.g. 'terrso.org' in the address bar.
![image](https://user-images.githubusercontent.com/92342777/147967759-17b51917-f8a8-43eb-b441-d8a1e4da7f7c.png)
