### ISSUE TITLE
Story Maps: sharing: show people with access (don't make it diclosable)

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#1159]
## Description
In Story Maps, when brining up the sharing screen, show "people with access" right away —don't hide it under a disclosure triangle.

<img width="946" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/86784/6cef1acf-6dd2-487f-b5bd-9b82771e3b20">

**Comment by Hanal-code** [comment]
@paulschreiber Can you share your rationale?

**Comment by paulschreiber** [comment]
- We have enough vertical screen space to show this
- It's extra work/cognitive load to click and disclose
- Google docs and Figma have the list shown by default (people will expect it)
