### ISSUE TITLE
Story Maps: clean up invite dialog

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#1161]
## Description
* The placeholder text "Enter one or more email address" is ungrammatical.
suggestion: "Enter email addresses"

* Add one or more people to edit your story map --> Invite people to edit your story map

* Drop "They will receive an email invitation to join this story map."

* Remove "Editors" label from text box.

* Add more space between email address and role

<img width="923" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/86784/bd4634de-b6a0-4725-9c25-ea885d9583e9">

**Comment by Hanal-code** [comment]
@josebui Can you 1) update the text change? (see the top two items in the list above)  2) add space between the email address column and Role column?   

@paulschreiber I disagree with other suggestions. E.g. removing the form label & helper text.

**Comment by DerekCaelin** [comment]
The changes specified by Hana have been resolved.

**Comment by paulschreiber** [comment]
This dialog is too complicated and has five different pieces of text to read/parse/understand.

The "Editors" label does not add value. It's redundant with the dialog title.

If it is important to explicitly state that people will receive email invitations, we should add that to the introductory sentence. I'd argue it's not — people understand what happens when you enter an email address.
