### ISSUE TITLE
Story maps: use different text for removing pending users

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#1164]
## Description
Removing a pending user shows this text:
>Remove XYZ from this story map
>XYZ will no longer be able to edit the “Poopy map”.

This isn't accurate, as the user hasn't accepted the invite yet.

Suggestion:
Withdraw XYZ's invitation to this story map?
XYZ will not be able to edit “Poopy map”.

**Comment by DerekCaelin** [comment]
This is resolved.
