### ISSUE TITLE
Bug: user invite to story map failed when user logged in with the wrong account. 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1196]
User who is invited to edit a story map can't because they are logged in with the wrong account. 

## Exchange
**User**
> Thank you very much for taking my editing suggestions into account! I have "invited" some colleagues to edit my draft storymap (Alvelal), but they tell me they can't open it, it tells them that the storymap is not found.
> I have done what you told me, in "Invite" and there I have put their emails... I don't know if I'm doing something wrong, but they can't access it.

**Derek**
> It looks like you invited two emails: <email1>, <email2> But it doesn't look like we have any users who have accepted those invites. [Person name] will need to accept an invitation she received and create an account in Terraso in order to edit the story map. Could she try to create a Terraso account and tell me if that works?

(Issue gets resolved without Derek knowing what happens - follows up)

**Derek**
>  Our theory is that [Person name] received an email invite at one email address, but ended up creating a Terraso account with another email address. So when she tried to access the story map with an account that wasn't the same one you invited, she ran into this bug.

**User** 
> Yes, that's what happened. [Person name] had previously registered with her gmail account and I invited her with her corporate account alvelal... and that's why she couldn't. And the same with [person name]. But I sent them an invitation to their gmail accounts and both have been able to log in.

Process to recreate:
1. Have terraso member create story map and invites someone
2. Non-terraso member receives invite email 
3. Non-terraso member logs in with a _different_ email address than the one was invited
4. Non-terraso member can't see the new story map to which they have been invited 

### Expected outcome:
Force the user to be logged in before accepting the invitation, that way we could have all the data to identify if the user that is accepting the invite is different from the expected user in the email

### Actual outcome
USer logs in to the wrong account, doesn't see story map in their personal ids. invitee asks for a direct link and, upon receiving, sees a blank page ('story map not found')

**Comment by DerekCaelin** [comment]
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/184b60ed-2748-4e4d-b4cd-1546ade95579)
This works for me, @Hanal-code @paulschreiber can we discuss copy?

Maybe: "[logged in user email] was not invited to edit [storymap name]. Please log in with the account that was invited to edit this story map."

**Comment by paulschreiber** [comment]
@DerekCaelin I left comments in the PR. 
> You can’t accept this Story Map invitation. You must be logged in using the email address shown in the invitation.

I agree adding the story map name would be helpful

**Comment by Hanal-code** [comment]
@josebui  How do we handle the use case that invitee's email address is NOT Google/MS/Apple email? e.g. hamriclr@colorado.edu

**Comment by paulschreiber** [comment]
@Hanal-code `hamriclr@colorado.edu` is a Microsoft account. If someone invites an email address not associated with a Google, Apple or MS account, the invitation won't be usable. But we have no way of knowing that in advance.

**Comment by Hanal-code** [comment]
For now I'd suggest to update the error message to: 
`You can’t accept the invitation to edit “{story map name}.” You must log in using the email address shown in the invitation.`

Also we can warn the inviters to use the supported email addresses (Google, Apple or MS account) instead of entering any email addresses.

**Comment by paulschreiber** [comment]
>Also we can warn the inviters to use the supported email addresses (Google, Apple or MS account) instead of entering any email addresses.

We have no way of knowing if a particular email address is tied to a valid Apple, Google or Microsoft account.

**Comment by Hanal-code** [comment]
Agreed that we have no way of knowing if a particular email address is **tied to** a valid Apple, Google or Microsoft account. Yet, we can suggest inviters to enter the emails from these three. It's hacky, but can be helpful when they know multiple email addresses for the invitee. 

**[Mockup]**
<img width="394" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/f0cfc56f-5842-4163-9433-7c089a71c243">


The current implementation forces the inviter to **resend** the invitation to the accepted email address. It's worthwhile to mention what are acceptable.
