### ISSUE TITLE
Design task - user selectable basemap in story maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1198]
Story Map enhancement mockup includes this basemap control update. 
```[tasklist]
### Tasks
- [x] Design Mock up
- [x] Copy doc
```

**ARTIFACTS**
- Design mockup:
- UI copy working doc: https://docs.google.com/document/d/15-KgOmLAR78QjJeruHOVSF0aDQGIq6htwenmBuS3nvw/edit

**Comment by DerekCaelin** [comment]
hana working on mockup

**Comment by Hanal-code** [comment]
@DerekCaelin @paulschreiber  Can you review the UI copy? https://docs.google.com/document/d/15-KgOmLAR78QjJeruHOVSF0aDQGIq6htwenmBuS3nvw/edit
