### ISSUE TITLE
Add LandScale to tools page

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1206]
As connections deepen between LandScale and Terraso, we are adding LandScale to our tools page.

**Title:** 
LANDSCALE

**Use this tool to:** 
- assess landscape sustainability performance
- validate results through LandScale validation and local review
- publish results on the LandScale platform

**System Requirements:** 
Modern web browser (Chrome, Edge, Firefox, Safari)

**Learn more:**
Learn more about [LandScale](https://www.landscale.org/initiative/)

**Go to**
Go to [Landscale](https://www.landscale.org)

Image:
![273627161-0fa31f27-9bc7-4197-b77b-b6c064d4ba04](https://github.com/techmatters/terraso-web-client/assets/10799815/f8fbfc3f-3318-49b5-a057-340a22e04de3)

**Comment by Hanal-code** [comment]
@DerekCaelin (1) Text: Can you add one or two more bullets for 'Use this tool to'?  (2) Thumbnail image: [Explore page](https://platform.landscale.org/explore) doesn't show the LandScale's coolness. Can you explore another pages?

**Comment by Hanal-code** [comment]
@DerekCaelin Do you have a screenshot of the assessment result's dashboard (Charts & graphs)? Can Edita share some images/screenshots from their PR/marketing packet? 
re: 500 error. I was logged in.

**Comment by DerekCaelin** [comment]
Some charts and graphs - do these look more descriptive of the value add of LandScale to you?

![image](https://github.com/techmatters/terraso-web-client/assets/10799815/eeefef5a-867a-4d17-809a-22e61da5e74c)

![image](https://github.com/techmatters/terraso-web-client/assets/10799815/de138310-dcd7-49e7-aa10-78224a982b98)

**Comment by DerekCaelin** [comment]
![landscale4](https://github.com/techmatters/terraso-web-client/assets/10799815/ba813e24-7a96-453f-a2fd-01d1759e85f8)

**Comment by DerekCaelin** [comment]
![landscale5](https://github.com/techmatters/terraso-web-client/assets/10799815/8546291f-35bd-4677-9da4-d24a265338eb)
@Hanal-code

**Comment by Hanal-code** [comment]
@DerekCaelin  The second screenshot with the bar chart looks good.

**Comment by Hanal-code** [comment]
Can you crop out the left pan -- just Dashboard in the background?

**Comment by DerekCaelin** [comment]
![landscale6](https://github.com/techmatters/terraso-web-client/assets/10799815/0fa31f27-9bc7-4197-b77b-b6c064d4ba04)

**Comment by Hanal-code** [comment]
the concept image looks good, Derek. You will create the image with a crisp logo, right? The resolution seems low.

**Comment by DerekCaelin** [comment]
The image we host in the tools page appears to be 400x270

**Comment by Hanal-code** [comment]
@paulschreiber Can you tweak the CSS to add a border? 
```
border-radius: 4px;
border: 1px solid rgba(0, 0, 0, 0.12);
```

**Comment by Hanal-code** [comment]
@DerekCaelin Can you clean up the image a little more? I think there's 1px white space at the top. That makes the top rounded corners look odd when the border is added. 
<img width="395" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/eae13170-5e96-4e8b-bbf2-cdedc712d41f">

**Comment by paulschreiber** [comment]
@Hanal-code add a border to what item(s) on the page?

**Comment by Hanal-code** [comment]
> @Hanal-code add a border to what item(s) on the page?

@paulschreiber The LandScale (dashboard) image.

**Comment by DerekCaelin** [comment]
@Hanal-code 
![273627161-0fa31f27-9bc7-4197-b77b-b6c064d4ba04](https://github.com/techmatters/terraso-web-client/assets/10799815/588c5b78-88d8-48f7-89d9-374c7bcc6221)

How does this look?

**Comment by paulschreiber** [comment]
I've updated staging with the new image.

**Comment by DerekCaelin** [comment]
@paulschreiber looks good, please submit to production.
