### ISSUE TITLE
Design task - Copy edits

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#1219]
UI copy working doc:
https://docs.google.com/document/d/1O8RzKsL6jRrWVBForaEmYJG6SZwjPWkPJuLDJsBrpqU/edit

**Comment by Hanal-code** [comment]
@DerekCaelin @paulschreiber Can you review the UI copy draft?

**Comment by DerekCaelin** [comment]
Review complete, transferring to Jose
