### ISSUE TITLE
Warn user before navigating away from data maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1231]
<img width="253" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/5ac5c98b-79be-4b91-8b86-97a059ca7b11">

## Description
Currently, users can navigate away from in-progress data maps and their work will be lost. We can warn users if they navigate away from a data map process in steps 2-5.

Requirements:
As a user making a data map, I want to be prompted to confirm that I want to navigate away from a data map if I am stages 2-5 of the process, so I don't accidentally lose my work.

**Comment by josebui** [comment]
Deployed to production
