### ISSUE TITLE
Remove '1 row selected' message in the tabular data tables 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#124]
## Description
MUI table seems to generate unnecessary message and paginate the short list in Member list view, Group list view, Landscape list view. 

Make the rows not selectable.

## Actual behavior
![image](https://user-images.githubusercontent.com/92342777/147980956-c994d069-bce6-4a43-8658-34a17c4a1390.png)

**Comment by paulschreiber** [comment]
@Hanal-code After reviewing other interfaces, we discovered it is common to show the pagination controls even when there is only one page of results.
