### ISSUE TITLE
Design - Design screen for when there are no mappable files

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1263]
GOAL: show the status and feedback to the user’s initiation of making a map.

**Comment by Hanal-code** [comment]
[MVP quick mockup] Show the message. 
<img width="1176" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/b431c931-7ff1-4aa4-9fde-e5b868cd5c27">
