### ISSUE TITLE
Plausible event - download png of map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1272]
Record in plausible when someone downloads a png of a map.

Goal: map.png

Properties:
- owner
- file
- fileID

**Comment by paulschreiber** [comment]
I renamed it to `map.png.download` to match `dataEntry.file.download`.

Also: this work was completed and the issue was closed. If you want to rename something (i.e. create new work), please create a new issue.

**Comment by DerekCaelin** [comment]
There might have been a communication issue; I sent this feedback to you over chat while we were discussing it. Please refrain from pushing a requested feature to production until it is cleared.
