### ISSUE TITLE
Can't make map with line based kml file

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1275]
I am unable to make a map from this simple line based KML file:

## To reproduce:

1. Upload [Raw track.kml](https://drive.google.com/file/d/1MoaiWmGGHjlj65okAvvoT086h8Iys6ro/view?usp=sharing)
2. make map
3. select  raw track file
4. click next
5. see error

## expected result
See map that looks like this:
<img width="500" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/fca8633d-3c37-41f7-b579-33fceb523166">

## actual result
<img width="500" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/9e71e03e-94d8-41e4-bcf5-d8fda4dd9069">

**Comment by DerekCaelin** [comment]
Get more samples of KML.

**Comment by DerekCaelin** [comment]
@josebui Additional links from our drive.

https://drive.google.com/file/d/1Dw3hqVq0-g88yE8aXwmxM6XOSeYo4JmK/view?usp=drive_link, https://drive.google.com/file/d/19lph3vwW9Psvb71p2cLeursiR3SWIT0A/view?usp=drive_link, https://drive.google.com/file/d/1-OM65HeQec3sECpQmjIA3RJI001CI2Qc/view?usp=drive_link, https://drive.google.com/file/d/1154zDWCQuDmRPrgi0yBp6tFFF3muD9f0/view?usp=drive_link, https://drive.google.com/file/d/11XRaieXtudwgOGdIipEoKsUp_OFg93ZZ/view?usp=drive_link, https://drive.google.com/file/d/1MoaiWmGGHjlj65okAvvoT086h8Iys6ro/view?usp=drive_link, https://drive.google.com/file/d/1Uq2mfLQOosGIkHD_PQ9xSDj_6hjPKR7q/view?usp=drive_link, https://drive.google.com/file/d/1tK1tt7fFyp8odCyRrKOX2ylYe-OFEpdE/view?usp=drive_link, https://drive.google.com/file/d/1BLG7f_CLWHK5hKaeEiDm0VL6NmVQ-H1C/view?usp=drive_link, https://drive.google.com/file/d/1g51b58_-Ap96qZ_1anF3rrKMl2mUz1wT/view?usp=drive_link, https://drive.google.com/file/d/1kVNb4yD-1y96QFQBWYDtCTFpamkNb-UX/view?usp=drive_link

**Comment by josebui** [comment]
This is on production now
