### ISSUE TITLE
Swap the icon in the intro text on the landscape boundary screen 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#1282]
## Description
The icons (Polygon tool, Basemap layer) show up in accurately. 

## Steps To Reproduce

1. Go to https://app.testing.terraso.net/landscapes/new or https://app.staging.terraso.net/landscapes/new
2. Fill out step 1 and proceed to the next to draw the boundary
3. Notice the text and the icon mismatch on the step 2 screen. `Use [icon A]  to change the background map`

## Expected behavior
Icon B should be displayed in `Use [basemap icon]  to change the background map`

## Actual behavior
A. polygon tool icon
B. Map layer icon 
<img width="794" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/91f53837-263f-4c9e-994c-33560e19e917">

**Comment by paulschreiber** [comment]
This is fixed on staging.
