### ISSUE TITLE
When viewing story maps, menu tabs are misaligned

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1284]
## Description
When the user views story maps, the menu (Home, Landscapes, Groups, Tools) is moved all the way to the left of the window; in other parts of the app, the menu is usually directly beneath the Terraso icon 

## Steps To Reproduce

1. Go to a story map: https://app.terraso.org/tools/story-maps/ymaodt1/alvelal
2. See issue

## Expected behavior
Menu is aligned as it is elsewhere in the app (e.g., the home screen)
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/b7ce247f-332c-434a-8f1c-c88ca5e961f0)

## Actual behavior
Menu is all the way to the left.
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/41f51d71-90b0-4833-b9fc-caa9ac22950e)

**Comment by paulschreiber** [comment]
This is fixed on staging.

**Comment by DerekCaelin** [comment]
@paulschreiber thanks, this looks right - please push to prod.
