### ISSUE TITLE
Data maps tool displays blank map instead of polygons from ESRI file

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1318]
When creating a data map from a particular Esri file, the map is blank: no polygons load.

## Steps To Reproduce
1. Go to a group or landscape
2. Upload [this Esri file](https://drive.google.com/file/d/1pQ1dfoVf_BTtB1xBuly9dUwG-3dk-NjT/view?usp=drive_link)
3. Select "make map" from the shared files module
4. Select the new file, click "next"
5. On "Appearance" tab, see issue

## Expected behavior
the map displays the polygons from the data file
<img width="1394" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/8374e386-c7fd-4014-93df-107bab9d8b1d">

## Actual behavior
The preview map is blank - no polygons are visible
<img width="1394" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/8ad33fee-333e-4c74-8955-a06677a782f1">

**Comment by josebui** [comment]
Deployed to production
