### ISSUE TITLE
Create public link for file

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1322]

**Comment by josebui** [comment]
S3 docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html

**Comment by Hanal-code** [comment]
@josebui  A couple of issues: 
1)  When the file access permission is changed to  `Anyone...` the warning message is expected to show up below the dropdown. See the screenshot. 
2) The snack bar message should be displayed inside the dialog, adjacent to the controls. 


![Image](https://github.com/techmatters/terraso-web-client/assets/92342777/12f8f3a0-3cb8-48d8-be3d-962ed32c4da0)



![Image](https://github.com/techmatters/terraso-web-client/assets/92342777/0c683e6c-eadf-4a4c-bb0a-96de8a86de8e)

**Comment by Hanal-code** [comment]
@josebui What does the default 'No one' option mean?  I thought 'Members' is the default for all shared files. 

USE CASE: File owner + Group member, Open group: https://app.staging.terraso.net/groups/test3. 


![Image](https://github.com/techmatters/terraso-web-client/assets/92342777/ef73a0ef-9201-40bd-a603-add20ec4d96a)

**Comment by DerekCaelin** [comment]
@josebui 
Update to design: The text for the banner for anonymous users should read, `Join Terraso and share files with your community`
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/34a0ba1e-30cb-468e-9814-aace13fe39c0)

**Comment by Hanal-code** [comment]
@josebui  The access control dropdown comments (e.g. Anyone on the internet....) are not the same font size & color.  Can you change (B)'s style to match to (A) in the screenshot? 
<img width="846" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/c0c1506c-e247-4462-a656-636fbcb039a3">
