### ISSUE TITLE
Add Alt-text to Terraso tools images

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1335]
https://app.terraso.org/tools

### Story maps
`A satellite map of a bend in a river, overlayed by a window containing a picture and a block of text.`

### Kobo Toolbox
`A phone, a laptop, and a tablet, each displaying a data collection form. The tool's logo is in the foreground.`

### LandScale
`A dashboard containing charts and graphs about a landscape. The tool's logo is in the foreground.`

**Comment by Hanal-code** [comment]
@DerekCaelin I moved the text above to a G-doc to work together. My suggested text is included in the doc. https://docs.google.com/document/d/1XgKCsiazpLYXjMphDYhMnHZZk4WSkkI9tkM2POx_DC8/edit
