### ISSUE TITLE
when making a data map with point-based dataset, changing the style results in an error

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1336]
When creating a data map from point data, changing the style on stage the "Appearance" stage results in an error. (The issue doesn't seem to occur with a polygon dataset like [this one.](https://drive.google.com/file/d/1q1IT6fhFp6JD6JqvwArGVvaB-lqHIcMy/view?usp=drive_link))

## Steps to reproduce.
1. Upload a file with lat/long coordinates to a group, eg: 
[Rocky Hill Bike Infrastructure.csv](https://github.com/techmatters/terraso-web-client/files/13503752/Rocky.Hill.Bike.Infrastructure.csv)
2. Select "Make Map"
3. Proceed to step 3, "Appearance"
4. Change "style" of map to "streets"
5. See error

## Expected behavior
- See "Streets" style on map

## Actual behavior
See error: `Oops, something went wrong. Try again in a few minutes.`

https://github.com/techmatters/terraso-web-client/assets/10799815/9534244e-380e-4a53-b6f3-78c0f23f7e70

**Comment by paulschreiber** [comment]
@DerekCaelin I have reproduced the problem. It happens with any style type. This is the backtrace:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getOwnSource')
   at Map.getSource (index.js:2:1)
    at Map.js:171:1
    at GeoJsonSource.js:32:1
```

**Comment by paulschreiber** [comment]
The problem comes from
```js
currentSource = map.getSource(name);
```

We can wrap this in a `try`/`catch` and not crash when an error occurs.

**Comment by paulschreiber** [comment]
@DerekCaelin Please verify this fix on staging.

**Comment by DerekCaelin** [comment]
@paulschreiber This is fixed
