### ISSUE TITLE
Design task - Create public link for file/map - Iteration

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1369]
Sharing file - the shared(link receiver) screen flow: [Mural ](https://app.mural.co/t/techmatters9109/m/techmatters9109/1697041314043/7f243901afc2dc0d8c537507c1fd68ce5a8b8c83?wid=0-1704483664033&outline=open)

**FINAL DESIGN MOCKUPS**:[ Figma](https://www.figma.com/file/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?type=design&node-id=2253-1958&mode=dev)
- Resource page screens: authenticated case and unauthenticated case
- Error page (Page-level error template)

**FINAL COPY FOR ERROR MESSAGES**:  [G-doc](https://docs.google.com/document/d/1T0yD5xBlFsoY8iFkWp__Aw2gxuc9cMVygxCRjJNge-I/edit)

**Comment by Hanal-code** [comment]
@DerekCaelin Can you take a look at the mockups of the Resource pages- auth and unauthenticated cases
https://www.figma.com/file/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?type=design&node-id=2217%3A2914&mode=design&t=W2lzDupPKwFPMUY1-1

**Comment by Hanal-code** [comment]
@DerekCaelin  @paulschreiber The 401 error case message has been added to the page-level error template in Figma.  
Review the UI text in this [G-doc](https://docs.google.com/document/d/1T0yD5xBlFsoY8iFkWp__Aw2gxuc9cMVygxCRjJNge-I/edit) please. Thanks!

**Comment by Hanal-code** [comment]
@DerekCaelin  Do you approve of the [design mockups](https://www.figma.com/file/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?type=design&node-id=2217%3A2679&mode=design&t=UuqcutRWcogRvBkr-1) above?

**Comment by DerekCaelin** [comment]
Yes, @Hanal-code - I approve.
