### ISSUE TITLE
Add alt text to a collection of icons and images 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1430]
view this list, add alt-text to designated issues: 
[updated G-doc for Engr] [Alt text/Tooltip for icons](https://docs.google.com/document/d/1s-g3MKCQdyZLFK67Khvq3mRYZrS1wcQqgAO4Y3Ws8Ro/edit)

- Find **the recommended fixes in the red column** in the doc (16 icons)

**Comment by Hanal-code** [comment]
@paulschreiber Summary of the task: 13 icons need tooltips and 3 need alt text. 

I also commented on a few for verification or further discussion. e.g. SVG link icon handling. 
After reading[ the accessible SVGs](https://www.deque.com/blog/creating-accessible-svgs/), I added the suggested fix to the doc, but I would like to hear your thoughts.

**Comment by Hanal-code** [comment]
@paulschreiber Can you match the Share file tooltip style (dark gray) to the Delete's style (mid-gray)? 
Go to: https://app.staging.terraso.net/groups/dataviz-test 
The majority of tooltips have a mid-gray background. 

**[Screenshot]**
<img width="638" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/3415d03f-d2a4-49fe-b92f-abe9df446a66">
