### ISSUE TITLE
In Terraso shared file module, display extensions for files

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1551]
We designed an experience for displaying files and extensions for the experience of making maps with data - the experience should extend to the main file/link sharing module.

## Current Implementation
<img width="967" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/6fd27193-9c94-4730-a2a1-45e2ea17ec56">

## Desired Implementation
<img width="967" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/22a8a08e-be03-419e-a9b5-6b896ffd71b5">

**Comment by Hanal-code** [comment]
**[MOCKUP] Tabular data layout change between large viewport and tiny viewport**
Note how the file name column(Column 1), metadata column(Column 2) and action column(Column 3) shift
<img width="1561" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/354dbbe2-ef2c-497b-98ef-ab5afa1b16d1">
