### ISSUE TITLE
On joining group, users see empty shared files module instead of files stored

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1599]
## Description
When joining a new group, the shared file module appears (as expected), but regardless of whether there are files the module is "empty" (no files listed). The files only appear once the page is refreshed. 

## Steps To Reproduce
1. Go to URL: https://app.terraso.org/groups/dereks-private-group/members
2. Click on Join Group
3. See issue

## Expected behavior
The shared file module loads, with files:
<img width="1373" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/fae57dc0-20e0-4ace-b189-4da9747a4856">

## Actual behavior
The shared fiel module loads, with no files visible
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/282a589e-59fb-4e28-953e-9369b975c6ad)

**Comment by paulschreiber** [comment]
@josebui Seems like a bug related to the membership list refactoring. Please also add a test for this.
