### ISSUE TITLE
Vertically align the file type icon with top  in Shared Files & Links module

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#1659]
## Description
When a file name wraps to multiple lines the icon shows up in the center of the cell vertically. It looks inconsistent from the single line item.  It also makes the tabular list less scannable.

## Steps To Reproduce

1. Go to Group or Landscape page: [[insert URL here](https://app.staging.terraso.net/groups/academic-research-test)]
2. Scroll down to 'Shared files and Links' module
3. Note  a long file/link title gets wrapped and the icon gets aligned center.

## Expected behavior
<img width="336" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/c267a863-9c53-4566-bb66-fa919db66583">

## Actual behavior
<img width="413" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/13cb578f-306b-409a-8b5f-c055d2b5fcfc">

**Comment by paulschreiber** [comment]
@Hanal-code Please verify this fix on staging.

**Comment by Hanal-code** [comment]
@paulschreiber The file type icon is still center-aligned. https://app.staging.terraso.net/groups/academic-research-test

**[SCREENSHOT]**
<img width="535" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/293adc0c-7663-4186-bd5c-c1cdaf06e0d7">

**Comment by paulschreiber** [comment]
@Hanal-code Looks like it didn't deploy properly to staging. Please try again.

**Comment by Hanal-code** [comment]
@paulschreiber For a 3-line file name, it works (Tiny viewport). But, for a 2-line file name, it's still center-aligned (Large viewport). 

<img width="950" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/6af374c3-7ee4-4eed-a16a-6035a726516f">

**Comment by paulschreiber** [comment]
Your original screen shot was from the mobile screen. I made fixes to the mobile screen. It was not evident from the description that you also wanted changes to the desktop screen. I can do that as well (the file name will have to be extremely long).

**Comment by paulschreiber** [comment]
@Hanal-code This has been fixed for desktop as well.

**Comment by Hanal-code** [comment]
✅ Verified.

**Comment by paulschreiber** [comment]
@Hanal-code this has been fixed.
