### ISSUE TITLE
Save and Cancel buttons are disabled on 2nd edit to description of shared files

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-web-client#1661]
## Description
Save and Cancel buttons are disabled (but they should be enabled) on 2nd edit to description of shared files and links.

## Steps To Reproduce
1. Go to URL: [here](https://app.staging.terraso.net/landscapes/carissa-test?scrollTo=shared-data-card-title)
2. Scroll down to the shared files and links
3. Add or edit one of the file or link descriptions
4. Make a change to the description, and click the Save button
5. Edit the same description again

## Expected behavior
The Save and Cancel buttons should be enabled

## Actual behavior
The Save and Cancel buttons are disabled, and the Save button shows a loading spinner indefinitely. (See image below)

## Additional context
- You can still save the new description by pressing Enter on your keyboard; it's just the buttons that don't work
- You can also refresh the page and the buttons will work again if you edit the description (but again, just the first time)
- Image: 
![Screenshot 2024-03-20 at 4 45 13 PM](https://github.com/techmatters/terraso-web-client/assets/5590815/a5893821-8215-4954-88ee-aed137dde26c)

**Comment by paulschreiber** [comment]
@knipec Please verify this fix on staging.
