### ISSUE TITLE
Localization missing in shared files and links for "<date>, by <author>"

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-web-client#1662]
## Description
Localization missing in "Shared files and links" card for "\<date>, by \<author>"

## Steps To Reproduce
1. Go to URL: [https://app.staging.terraso.net/landscapes/carissa-test](https://app.staging.terraso.net/landscapes/carissa-test)
2. Set the language at the top to Español
3. Scroll down to the Shared Files and Links card
4. Look at the text displaying the date and author

## Expected behavior
I see "20 mar 2024, por Carissa Knipe" 
(or something in Spanish, not "by")

## Actual behavior
I see "20 mar 2024, by Carissa Knipe"

## Additional context
- The ", by" part is hard-coded in SharedDataEntryBase.js and should be moved to however we do localization:  
```
<Grid item xs={11} md={3} order={{ xs: 8, md: 6 }}>
    {formatDate(i18n.resolvedLanguage, dataEntry.createdAt)}, by{' '}
    {t('user.full_name', { user: dataEntry.createdBy })}
</Grid>
```
- ![image](https://github.com/techmatters/terraso-web-client/assets/5590815/91ce7474-6b26-4ed6-9575-441cc78851c4)
- If we plan to support other languages we may want the flexibility to move date, author, and static string parts of the whole phrase structure around

**Comment by paulschreiber** [comment]
@DerekCaelin Please verify this on staging.

**Comment by paulschreiber** [comment]
@DerekCaelin test.

**Comment by paulschreiber** [comment]
@DerekCaelin testing.

**Comment by knipec** [comment]
This is not yet in staging -- @paulschreiber I replied to your comment on the PR.
Should I still put it in staging before resolving all PR comments?

**Comment by knipec** [comment]
Ok now it's in staging :)

**Comment by Hanal-code** [comment]
:white_check_mark: Verified. 
[screenshot]
<img width="280" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/d3e94d8a-ce4e-4845-a8e0-d28fe3a30b70">

**Comment by DerekCaelin** [comment]
@knipec Confirmed please push to prod.
