### ISSUE TITLE
Web URL missing from preview in shared file module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1690]
## Description
Shared links used to reveal an extension 

## Steps To Reproduce

1. Go to URL: https://app.terraso.org/landscapes/sacred-sierra
2. Join the landscape
3. Scroll down to the shared file module where there is at least one URL shared

## Expected behavior
We see the preview URL in the area where the file extension is visible
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/b8ec6078-fe61-420e-bf00-520d3eb9cb15)

## Actual behavior
the preview URL extends over the extension and the size field.
![image](https://github.com/techmatters/terraso-web-client/assets/10799815/fa78610a-d10c-4387-8110-d13b8759bb6b)

**Comment by paulschreiber** [comment]
@knipec Looks like this broke with the file extension work: https://github.com/techmatters/terraso-web-client/pull/1660

Please fix this bug and add a test to ensure the domains appears.

**Comment by paulschreiber** [comment]
@DerekCaelin Carissa is working on this.

**Comment by knipec** [comment]
The fix is on staging now
