### ISSUE TITLE
Accessibility review/audit

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#172]
## Description
Review and improve the accessibility of the Terraso web application, using both automated tools and human validation.
- [ ] Language selector needs to show focus. (Reference: https://www.a11yproject.com/checklist/#keyboard)
- [ ] Make the main navigation at top navigable using the tab key. (Reference:https://www.w3.org/WAI/tutorials/menus/)
- [ ] Add ARIA landmark roles (Reference: https://webaim.org/techniques/aria/#landmarks)
- [ ] Check the form fields and validation  (https://webaim.org/techniques/formvalidation/)
- [ ] Add 'Skip to main' button for users to jump to the main content. (Reference: https://webaim.org/techniques/skipnav/) 
- [ ] Check off the items from https://www.a11yproject.com/checklist/
- [ ] Color constrat check (https://webaim.org/resources/contrastchecker/)
- [ ] Check Semantic HTML usage (https://www.w3schools.com/html/html_accessibility.asp)
- [ ] Check tab order (https://webaim.org/techniques/keyboard/tabindex)
- [ ] Screen reader starts on footer (Reader: https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en)

**Comment by josebui** [comment]
React Accessibility docs: https://reactjs.org/docs/accessibility.html

**Comment by josebui** [comment]
Mui docs: https://mui.com/system/screen-readers/#foo

**Comment by josebui** [comment]
Material UI docs: https://material.io/design/usability/accessibility.html#understanding-accessibility

**Comment by josebui** [comment]
Review results:
- https://docs.google.com/document/d/1z7x-H77Mepzgy1dvte67iJ00nJrf-lLE0ecw9A6hnzY/edit#heading=h.lt27wahcreji
- https://docs.google.com/document/d/1oKc2ojASfOpJtqAMx3sMbUtOB6_ZdHlSOSqjyLdfm8Y/edit#heading=h.68amq2fgr3km

**Comment by josebui** [comment]
Finished a11y review
