### ISSUE TITLE
Error page (404 and 500 errors)

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#183]
## Description
Create error page templates/pages for 404 and 500 errors.
Non Engr tasks: https://trello.com/c/efmFDKjR/40-list-global-error-state-and-draft-helpful-error-messages

MVP:
- [x]  simple 404 error page design
- [ ] implementation

**Comment by Hanal-code** [comment]
@josebui  Please review[ the UX spec for the 404 error: ](https://docs.google.com/document/d/1jpAVzmIV9D0-fe38bGvg0viSI-te2Niw6YfOa1j7avA/edit#heading=h.c32ngmn2sr3y) and let me know if anything is missing/unclear.

**Comment by Hanal-code** [comment]
Image:
![goats-450px](https://user-images.githubusercontent.com/92342777/154713244-601d1e4a-96a4-480d-80fc-0b2ccd702b38.png)

**Comment by josebui** [comment]
Hey @Hanal-code, for this one we also need to know how this will look for the desktop view

**Comment by Hanal-code** [comment]
@josebui  Both the mobile and the desktop views are in Figma file. https://www.figma.com/file/uYtYqNvefGUPXyA2oQgp7n/error-page?node-id=0%3A1
