### ISSUE TITLE
Add map layer to story map - design "pending" map layers

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1940]
While adding Map Layers to a story map, allow users to see "pending" map layers (that is, map layers that have been created but are not yet available in Mapbox). 

Enhances:
- #785 

## References
Figma:
[Open List ](https://www.figma.com/design/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?node-id=2466-2216&t=mm4bHaAX6mc0bvwN-1)showing processing status, with an alternative design below it

## Acceptance Criteria
- [x] As a user who has created a map in a landscape or group, but whose map is still being processed by Mapbox, I want to see in the "add map layer" experience that my map layer is registered but not yet ready, so that I know that I need to try again in a few minutes.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I designed two options, as you'll see on the Figma. I went with the word "processing", because "pending" could be confusing - pending what? Approval from someone? 

I'm also wondering... will the card automatically update when the map layer is processed and ready to use? Or does the user need to refresh the page? The first would be ideal.

**Comment by DerekCaelin** [comment]
I like the "try again in a few minutes" line because it lets the user know what to do. @josebui, how difficult is it to have card update automatically when the map layer is processed, so that the user doesn't need to refresh?

**Comment by josebui** [comment]
Right now we don't have the functionality implemented (websockets) to update the card automatically, I think the effort just for that mechanism by itself should be arounf 8 points. 

As far as I can see the work will be to just add a new card with a different style, the first one seems like it will need a little more effort than the second one, but the difference should be between 2 and a 3 points

**Comment by DerekCaelin** [comment]
Thank you! @CourtneyLee333 I think we should go with version 1 from Figma, because that gives the user instructions that they should `try again in a few minutes.` A later enhancement can be to have automatic updates. What do you think?

**Comment by CourtneyLee333** [comment]
Sounds good to me!
