### ISSUE TITLE
Add map layer to story map - display pending map layers

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1941]
While adding Map Layers to a story map, allow users to see "pending" map layers (that is, map layers that have been created but are not yet available in mapbox). See parent issue for details. 

## References
- #785 
- [Tests](https://docs.google.com/spreadsheets/d/1JY_NVWZRcv95wrp-PgP4Ku4_YgihFpf8K0p_l1pq9yE/edit?gid=0#gid=0)

## Designs
[Figma](https://www.figma.com/design/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?node-id=2466-2216&t=mm4bHaAX6mc0bvwN-1)

## Acceptance Criteria

- [ ] As a user who has created a map in a group or landscape, I want to see that this map is coming, but not yet available, as a layer in the "add map layer" experience

**Comment by DerekCaelin** [comment]
Jose says this is a size 3 task.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I've [written some tests](https://docs.google.com/spreadsheets/d/1JY_NVWZRcv95wrp-PgP4Ku4_YgihFpf8K0p_l1pq9yE/edit?gid=0#gid=0) - would you take a look at the design Jose implemented on staging?

I'm interested in your opinion on when the client should check to see if the desired map is available. Current behavior is:
1. Edit map
2. Add map layer
3. [Check]

The effect being that you need to close the "Edit map" window and return to check again. Should the app check every time you select "add data layer" ?

**Comment by CourtneyLee333** [comment]
@DerekCaelin How do I create a map?

**Comment by DerekCaelin** [comment]
Incredibly, I can't find a tutorial on the Terraso website, so I wrote [one.](https://docs.google.com/document/d/1YJS7ickmB0nQbAwEt-GtQEVL8fOp8BWydMGhEzXtElM/edit)
