### ISSUE TITLE
Storymaps: Design experience for new available map layer

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#2417]
As of September 2024, the Map Layer selector UI will display a "Pending" notification over a map layer if Mapbox was processing the map when the UI is opened. If Mapbox completes the processing and the map is available, this pending notification will not change until the user closes and reopens the window. How might we let the user know that the map is now ready without them leaving the window?

## References
We think websockets will allow the client to cheaply identify when a change is happening on the server.  Jose did research on how to enable this.

## Design
[Figma file](https://www.figma.com/design/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?node-id=2731-825&t=n55ci22LO7206Tpy-1)

## Acceptance Criteria
- [x] Design UI updates to the map layer selector. (What does the user see when the map is now available for use in story maps?)
- [x] Engineering feedback

**Comment by CourtneyLee333** [comment]
From Derek on Slack: Courtney, let us know if you think a meeting would be helpful to consider designs. Maybe the smallest possible version would just be to replace the ["Processing" label](https://www.figma.com/design/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?node-id=2588-790&node-type=frame&t=fGzD3NsW3dhpkECB-0)  with a "Ready" label? up to you.

**Comment by CourtneyLee333** [comment]
See the Figma file in this issue's description. I went with the super simple approach of reusing the chip with some style changes. There is a note at the top of the design to describe the behavior.

**Comment by paulschreiber** [comment]
Design looks good to me.

**Comment by DerekCaelin** [comment]
Looks great.
