### ISSUE TITLE
Add feature to update Landscape's area polygon

### ISSUE THREAD

**Issue by cacarrara** [techmatters/terraso-web-client#250]
- The feature will be only available for Landscape managers;
- It should be added a new button below the current map, only visible for Landscape managers. This button will redirect the user to a proper page to perform the edit action;
- The new page will have two major components: a GeoJSON file input and a Map for polygon preview;
  - Once the GeoJSON file is added into the file input, the web client will have to read it and update the preview map with the polygon;
  - The user might add different files to have new preview visualizations;
  - Below the preview map, a confirmation button will update the `areaPolygon` attribute of Landscape with the informed GeoJSON content using the API;

### Design
![image](https://user-images.githubusercontent.com/348237/155762186-32607c23-4c70-424a-b013-105064a49401.png)
--
![image](https://user-images.githubusercontent.com/348237/155762282-869ac011-a105-4a0f-b2dd-b0513dbd1bbb.png)

**Comment by josebui** [comment]
Spec: https://docs.google.com/document/d/1CFe8hjRh5Ak3wFL98Y6XUiMiPS3u4DcpxUE6tksXXCI/edit#heading=h.l6dghai1f0iv

**Comment by Hanal-code** [comment]
- [ ] Change the file format error message to 'A wrong file format. You can upload a GeoJSON file only.'  [See the all error messages in the spec doc](https://docs.google.com/document/d/1CFe8hjRh5Ak3wFL98Y6XUiMiPS3u4DcpxUE6tksXXCI/edit#):

**Comment by Hanal-code** [comment]
the map overlaps with the footer. 
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/92342777/158269289-6adf142a-6f40-4e03-8dca-c131d2733e89.png">
