### ISSUE TITLE
Web App: Link to new terms of service and privacy policy

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#2518]
Tech Matters (and Terraso) have a new terms of service. Update the Terraso web app.

- [x]  Footer: add Terms of Service before Privacy Policy, and link to https://terraso.org/terms-of-service
- [x] [Sign in screen](https://app.terraso.org/account): change “If you don’t already have a Terraso account, signing in will create one in accordance with our [privacy policy](https://techmatters.org/privacy-policy).” to “If you don’t already have a Terraso account, signing in will create one in accordance with our [Terms of Service ](https://terraso.org/terms-of-service) and [Privacy Policy](https://techmatters.org/privacy-policy).”
- [x] Translations: translate the changes above

**Comment by paulschreiber** [comment]
TOS link has been added to the Google OAuth screen. It is pending Google approval.

**Comment by DerekCaelin** [comment]
That's great - will you also be able to tackle this?
[Sign in screen](https://app.terraso.org/account): change “If you don’t already have a Terraso account, signing in will create one in accordance with our [privacy policy](https://techmatters.org/privacy-policy).” to “If you don’t already have a Terraso account, signing in will create one in accordance with our [Terms of Service ](https://terraso.org/terms-of-service)and [Privacy Policy](https://techmatters.org/privacy-policy).”

**Comment by paulschreiber** [comment]
@DerekCaelin Login screen is updated on staging.

**Comment by DerekCaelin** [comment]
Looks great! Please push to production.
