### ISSUE TITLE
uMngeni landscape profile is missing the landscape description

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#253]
## Description
uMngeni landscape profile is missing the landscape description. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: 'https://app.terraso.org/landscapes/umngeni'

## Expected behavior
A description about the landscape like other landscapes. 

## Actual behavior
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/92342777/156795371-175cba8f-ea6b-4265-a9a9-0e845b0cb81b.png">

**Comment by cacarrara** [comment]
Fixed.
