### ISSUE TITLE
Landscape's the country name and the continent info is reversed 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#254]
## Description
The conventional order of the continent and country info is the country first and then the continent. e.g. 'Guyana, South America'
Terraso displays this info in a reverse order. Is it intentional for some reasons? 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: 'https://app.terraso.org/landscapes/rupununi'
2. See error

## Expected behavior
<img width="185" alt="image" src="https://user-images.githubusercontent.com/92342777/156797741-4c87d0b0-df28-4a52-b00d-43322ba016d4.png">

## Actual behavior
<img width="275" alt="image" src="https://user-images.githubusercontent.com/92342777/156797355-07811743-2c7d-4a07-8665-6f72d047fa47.png">

**Comment by cacarrara** [comment]
Fixed
