### ISSUE TITLE
Bison Hillock Map not displaying correctly

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#260]
## Description
The leaflet map showcasing Bison Hillock has an error - the map does not display, and instead, a "file not found" graphic is displayed. This appears to happen with the map is of a single point, rather than a polygon.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/10799815/157708477-5b5bc9b2-3d04-4745-a83c-784e947ed2e8.png">

## Steps To Reproduce
1. Go to https://app.terraso.org/landscapes/bison-hillock
2. Look at map

## Expected behavior
Bison Hillock should be represented by a polygon. I've uploaded [a new polygon](https://airtable.com/appIE3c0ExjlY2N7l/tblnmj9Dv0GJJIhAm/viwETromIx4i5uRCU/rec7fLUCIszEoyQZj?blocks=hide) to AirTable that should resolve this issue.

**Comment by paulschreiber** [comment]
Fixed on staging.

**Comment by paulschreiber** [comment]
Fixed on production.
