### ISSUE TITLE
Alto Mayo Landscape boundary is missing the area highlight

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#265]
## Description
the map stopped displaying the blue highlight that used to demarcate the landscape boundary & area in the map after updating the GeoJSON file for my landscape. Only the boundary. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: [(https://app.staging.terraso.org/landscapes/cobiocom)](https://app.staging.terraso.org/landscapes/alto-mayo)'
2. Click on 'Update Geo...' button to upload a GeoJSON file
3. complete uploading a GeoJSON file to your landscape.
4. See the new boundary has drawn on the map but the area highlight is missing 

## Expected behavior
<img width="551" alt="image" src="https://user-images.githubusercontent.com/92342777/158819562-c5aa1840-1831-457e-8ab1-7d0b1984fc13.png">

## Actual behavior
<img width="431" alt="image" src="https://user-images.githubusercontent.com/92342777/158819625-73268db6-98dc-46d3-9165-a39b1d42bc20.png">

**Comment by josebui** [comment]
Closing issue. The higlight is related to the geojson content and not the feature
