### ISSUE TITLE
Finesse the UI text and the spacing for the How-to below the landscape map

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#266]
## Description
1. Change the ui text from _'How to improve the geographic info'_ to _'How to improve the landscape boundary'_ 
2. Place the period before the icon.  Currently it's displayed after the icon. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: 'https://app.staging.terraso.org/landscapes/alto-mayo'
2. Scroll down to 'How to improve...'
3. Click 'How to ...' and view the paragraph... 

## Expected behavior
<img width="567" alt="image" src="https://user-images.githubusercontent.com/92342777/158899908-15d0a71f-a7ce-4021-8329-b852be69d859.png">

## Actual behavior
**See Descriptions above**
<img width="550" alt="image" src="https://user-images.githubusercontent.com/92342777/158899650-58fe9eb9-d94a-4693-a07e-1673ade2e734.png">

**Comment by paulschreiber** [comment]
Addressed by #274.
