### ISSUE TITLE
Website for Altiplano Estepario leads to 404

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#280]
## Description
Altiplano Estepario's "Website" has changed. The "Website" link on the Altiplano Estepario Terraso page should now direct to: https://4returns.commonland.com/landscapes/revitalizing-land-and-community-in-the-altiplano/ 

## Steps To Reproduce
1. Go to: https://app.terraso.org/landscapes/altiplano-estepario
2. Click on the "Website": https://4returns.earth/portfolio-items/restoring-the-landscape-by-building-a-movement/AlVelAl
3. See 404

**Comment by cacarrara** [comment]
Website updated.
