### ISSUE TITLE
Update Altiplano Estepario Boundary

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#287]
## Description
We've been told that the Altiplano Estepario landscape boundaries have been updated. The new file is on AirTable [here.](https://airtable.com/appIE3c0ExjlY2N7l/tblnmj9Dv0GJJIhAm/viwETromIx4i5uRCU/recRBRHJ05FXIPR3j?blocks=hide)

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.staging.terraso.org/landscapes/altiplano-estepario

**Comment by paulschreiber** [comment]
Updated on production and staging.
