### ISSUE TITLE
Error creating Landscape with uploaded polygon (On Staging)

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#328]
## Description
After uploading a geojson file in the  "Create Landscape" workflow, I received an error upon hitting "Create Landscape"

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.

1. Go to URL: 'https://app.staging.terraso.org/landscapes/new'
2. Fill out basic landscape info
3. Select "Upload a GeoJSON file"
4. Click "Select File"
5. Upload [Rocky Hill geojson file.](https://drive.google.com/file/d/1q1IT6fhFp6JD6JqvwArGVvaB-lqHIcMy/view?usp=sharing)
7. Click "Create Landscape"

## Expected behavior
New landscape page is created

## Actual behavior
Snackbar presents large error message:
`Oops, something went wrong. Please try it again in a few minutes. (Error: Variable "$input" got invalid value {"areaPolygon": "{\"type\":\"FeatureCollection\",\"name\":\"Rocky Hill\",\"crs\":{\"type\":\"name\",\"properties\":{\"name\":\"urn:ogc:def:crs:OGC:1.3:CRS84\"}},\"features\":[{\"type\":\"Feature\",\"properties\":{\"shape_area\":\"384836740.31\",\"shape_len\":\"92462.1469935\",\"town\":\"Rocky Hill\",\"town_no\":\"119\"},\"geometry\":{\"type\":\"MultiPolygon\",\"coordinates\":[LONG STRING OF COORDINATES]", "description": "A town on the banks of the Connecticut River. For decades, our community has adopted policies to preserve and maintain our spaces for agriculture and parks. We continue to explore the path of sustainability.", "location": "United States", "name": "Rocky Hill", "website": "https://www.facebook.com/groups/304141138466541"}. In field "areaPolygon": Unknown field.)`

<img width="375" alt="image" src="https://user-images.githubusercontent.com/10799815/166742240-3cd66533-9ab3-4cd7-9e78-e97131b98ec1.png">

**Comment by cacarrara** [comment]
@josebui this looks like an attempt of using the feature before the staging version be updated. Can you confirm that?
