### ISSUE TITLE
Cropped profile images in members lists

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#329]
## Description
The user's profile image is slightly cropped when viewed in a "Members List" at a group or landscape level.

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.staging.terraso.org/landscapes/rocky-hill
2. look at member list

## Expected behavior
I expect to see a round image with the faces of users.
![image](https://user-images.githubusercontent.com/10799815/166773591-e68b34af-fd0d-4c1e-888b-2d9dd40dd6f2.png)

## Actual behavior
Instead, the image is slightly cropped on all sides.
![image](https://user-images.githubusercontent.com/10799815/166775569-e08a2df3-176f-4a48-a640-aa978d6be879.png)

**Comment by paulschreiber** [comment]
This looks okay for me on Chrome 100 on macOS:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/86784/166795064-3cf7b9d5-edb2-4611-b34c-c0c80c07bf58.png">

- Can you reproduce on Chrome? 
- What browser/version are you using?

**Comment by DerekCaelin** [comment]
I encounter the problem on Brave (Chromium 100).

But not on Firefox:
![image](https://user-images.githubusercontent.com/10799815/166799215-44a75d65-7311-48b5-bae7-19b8b54a51ad.png)

**Comment by DerekCaelin** [comment]
The issue appears related to the zoom of my browser: [Video Link](https://drive.google.com/file/d/14Isev6G5h0sMYOcVzwWQ4cjHYbQCjJbs/view?usp=sharing)
