### ISSUE TITLE
Remove Most Groups from Group List

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#342]
## Description
As we've developed Terraso, we've used Groups created by product as a standin for the co-design partners we've been working with. These partners will likely want to create and name their own groups. Therefore, all groups except for a few should be removed from Terraso. The exceptions are:

* Norwegian Parks Association
* Rocky Hill Sustainability Team

**Comment by paulschreiber** [comment]
Done.
