### ISSUE TITLE
Fix duplicated "accountMembership" information in groups

### ISSUE THREAD

**Issue by josebui** [techmatters/terraso-web-client#345]
## Description
The "accountMembership" data is not always under the same strucuture for groups, on some places it is in `group.accountMembership` and in some other places it is in `group.membersInfo.accountMembership` it should be always in `group.membersInfo.accountMembership`

**Comment by shrouxm** [comment]
@josebui closing because i think this is no longer true after the client migration work, lmk if still relevant!
