### ISSUE TITLE
When Manager, Missing Space on Group "About" module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#356]
## Description
When manager of a group, the "Update Group" button is too close the the rest of the text in the "About" module.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/10799815/170119009-d49378f4-26bd-4198-972c-9ee965431feb.png">

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Be manager of a group
2. Navigate to group
3. See "About section"

**Comment by paulschreiber** [comment]
Fixed with https://github.com/techmatters/terraso-web-client/commit/63c9df154f7e548ce074fcb0a878e818f500d727.
