### ISSUE TITLE
On mobile, no margins for text during file upload

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#358]
## Description
The text prompt to select a file appears crowded to the left on a mobile interface.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/10799815/170120005-8822afbc-0838-41bb-b270-af34199a7fb9.png">

**Comment by paulschreiber** [comment]
Fixed with 4d06892027da8fb352d694f9160756d06c2c89fe.
