### ISSUE TITLE
Not enough spacing between share buttons

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#369]
## Description
There are no spaces between the share buttons using the "Share Landscape" feature.

Current
![image](https://user-images.githubusercontent.com/10799815/170742466-39855faa-5e73-4fac-a771-6722b3322edc.png)

Figma Design
<img width="457" alt="image" src="https://user-images.githubusercontent.com/10799815/170742430-062a3d55-5c99-47c6-80db-2431b885935c.png">

**Comment by Hanal-code** [comment]
I saw the different spacing in the Staging env. Landscape Share dialog has the negative space as opposed to Group Share dialog has none. How weird. 
In PROD, both dialogs has no space between buttons independent from the viewport size. 

Can you increase the Dialog width to address the space and the Copy the link module width? The current width doesn't allow the user to see what the URL is.

**Comment by paulschreiber** [comment]
@DerekCaelin there is definitely space there. Please provide more details (uncropped screen shot, viewport size, browser).
