### ISSUE TITLE
Landscape website URL input erred without changing anything

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#371]
## Description
Landscape website URL input erred without changing anything in Landscape profile form.
This is a valid URL and didn't err before. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.terraso.org/landscapes/acus-peninsula-galera-san-francisco
2. Click on 'Update Landscape' button
3. Scroll down to 'WEBSITE' input field and see the previously entered url: https://www.regen.network/case-studies/eco-cacao/
4. Click Save change 
5. See the URL error message. Be stuck 

## Expected behavior
No error as the URL input wasn't touched at all. 

## Actual behavior
<img width="473" alt="image" src="https://user-images.githubusercontent.com/92342777/170781496-425335b9-bdc4-45a3-a28a-a255f34ea2c9.png">

**Comment by paulschreiber** [comment]
@Hanal-code I am unable to reproduce this. Does it still happen for you? I can reproduce the error if I add a leading tor trailing space to the URL.

**Comment by Hanal-code** [comment]
@paulschreiber I can't reproduce the error any more, either.
