### ISSUE TITLE
Remove the placeholder text when the input field is activated by the prompt

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#388]
## Description
The placeholder text inside the input field should not persist when user move the mouse pointer to enter letters. Persisting placeholder text can mislead  

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: ['https://app.staging.terraso.org/groups/academic-research-test/upload']
2. Add a data file
3. Notice the File description input field appears with a short placeholder text.
4. Move the prompt to File description input field. 
5. Notice the placeholder text persists instead of clearing the input. 

## Expected behavior
The text input field clears to blank for the user to start typing as the prompt moved inside the input. 

## Actual behavior
the placeholder text persists until the user enters the **first letter.**

<img width="515" alt="image" src="https://user-images.githubusercontent.com/92342777/171505764-801c4d2b-9bd2-44d9-aca1-8bb01298cad3.png">

<img width="141" alt="image" src="https://user-images.githubusercontent.com/92342777/171505958-320a35d1-9060-4877-82f6-22289a47a8f0.png">

## Additional context
This interaction pattern should be applied all text input field to prevent the confusion.

**Comment by paulschreiber** [comment]
This is correct behaviour for placeholder text. This is how it works across browsers. I confirmed this with a plain HTML file in Firefox, Safari and Chrome.

**Comment by paulschreiber** [comment]
>Some input fields indeed requires user to delete the placeholder text.
Then that's not really placeholder text. Placeholder text isn't editable by users.

It'd be weird if our site behaved different from every other site. People would think it was broken.

**Comment by Hanal-code** [comment]
I disagree that our target users would pay that close attention to the input field's placeholder text's disappearance timing.
