### ISSUE TITLE
Uploading map boundary screens doesn't show the page title on load

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#397]
## Description
In the creating landscape workflow, two screens of uploading the map boundary didn't scroll up when user tap Next button. 

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.terraso.org/landscapes/new in tiny viewport 
2. Fill the form and tap 'Next'
4. Notice the screen is showing the bottom half of the screen in the viewport 

## Expected behavior
The top portion of the screen in the viewport. 

## Actual behavior
<img width="356" alt="image" src="https://user-images.githubusercontent.com/92342777/171658959-7a885d70-2cac-4165-8274-a0315748b42d.png">

**Geojson file update screen**
<img width="370" alt="image" src="https://user-images.githubusercontent.com/92342777/171659100-9d47c1c2-bfbc-440d-9634-be595995f299.png">

**Comment by paulschreiber** [comment]
@Hanal-code this is on staging to verify.

**Comment by Hanal-code** [comment]
Verified 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/92342777/172244808-cf270773-54e5-42db-a4f2-95ae421bbef2.png">
