### ISSUE TITLE
can't log in to the staging env

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#444]
## Description
A clear and concise description of the problem.

## Steps To Reproduce

1. Go to URL: https://app.terraso.org/account
2. Browse a few pages. 
3. Go to URL: https://app.staging.terraso.org/account
4. See the error message (screenshot below) when click to log in using Google account. 
5. Notice being stuck in this page.

## Expected behavior
Being able to log in to the staging env and the prod env using the same browser.  

## Actual behavior
<img width="524" alt="image" src="https://user-images.githubusercontent.com/92342777/178009009-ae611968-7dad-435e-9bf3-0ecdc432312d.png">

**Comment by paulschreiber** [comment]
This should be fixed now. Staging is now app.staging.terraso.net and no long has a cookie conflict.
