### ISSUE TITLE
Home screen: vertically align group and landscape boxes

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#463]
## Description
On the home screen, the empty group and landscape boxes are different heights and not vertically aligned. Make them the same height.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/86784/180299184-4c62802c-6e72-4681-a9db-1b8bc3082437.png">

**Comment by shrouxm** [comment]
closing because no longer relevant to the home screen UI, let me know if you disagree

- they won't be vertically aligned as soon as a landscape or group is joined
- the parallel columns generally speaking are not expected to be aligned
