### ISSUE TITLE
Put landscape map on standalone page, allow unauthenticated access

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#478]
![Image](https://user-images.githubusercontent.com/10799815/230678110-02a76fbe-cd1d-4c3c-8f75-cab25ef13841.png)

## Description
Allow the map from https://app.terraso.org/landscapes to be embedded on Terraso.org and Landscapes.global. This will replace [the landscape map currently on the Terraso website.](https://terrasostg.wpengine.com/landscapes/) 

Dependent on #820 

### Product
- [x] As PM, I want an embed code which allows me to place the landscape map on Terraso.org or Landscapes.global
- [ ] As an unauthenticated user seeing the Landscapes map on a website, and my experience should match those of users of the site
- [ ] As an unauthenticated user who navigates to Terraso, I should be prompted to log in once I reach Terraso

QA:
- https://github.com/techmatters/terraso-web-client/issues/863

**Comment by paulschreiber** [comment]
@DerekCaelin you can view the map on https://app.staging.terraso.net/landscapes/map and in a page at https://terrasostg.wpengine.com/landscapes/

Note that on mobile, the page version will have extra whitespace. That will get fixed when the staging site is updated with the new design.

**Comment by DerekCaelin** [comment]
Hi Paul,

This is really cool! One issue - landscape cards should link to the landscape page on Terraso: https://github.com/techmatters/terraso-web-client/issues/863

What is the embed code for this map (so I can share it with the 1000L people for landscapes.global)

Will the embed stay the same if we update the basemap and colors?

**Comment by paulschreiber** [comment]
As noted above, the map is at `https://app.staging.terraso.net/landscapes/map`. The production map will be at `https://app.terrsso.orrg/landscapes/map`

You would embed it like so:
```
<iframe src="https://app.terrsso.org/landscapes/map" width="XYZ" height="ABC"></iframe>
```
