### ISSUE TITLE
Track user logins using Plausible

### ISSUE THREAD

**Issue by emilybguo** [techmatters/terraso-web-client#484]
## Description
Add as a Plausible event the number of times people hit the `sign in with xyz` button, tagging each event as a "Google" or "Apple" log-in.

**Comment by paulschreiber** [comment]
@david-code was this completed with other Plausible work?

**Comment by david-code** [comment]
> @david-code was this completed with other Plausible work?

No, I must have missed this. We have information on when users sign up, but not when they sign in.

**Comment by paulschreiber** [comment]
This is done on staging. Look for the `User login` event in Plausible.

**Comment by DerekCaelin** [comment]
Confirmed and thank you.
