### ISSUE TITLE
Long text exceeds dimensions of pop-up

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#554]
![image](https://user-images.githubusercontent.com/10799815/193585049-88e88b88-e46c-498e-be0a-167598987da8.png)

## Description
I included a long URL of a photo with as a data point in a pop-up. The text exceeded the dimensions of the popup

## Steps To Reproduce

1. Join Rocky Hill
2. Look at Link: https://app.terraso.org/landscapes/rocky-hill/map/known-bike-racks
3. Click on a point with a URL attached

## Expected behavior
Extremely long text without spaces should wrap.

## Actual behavior
Extremely long text spills over the popup onto the map.

**Comment by paulschreiber** [comment]
This should wrap, not truncate. Also: URLs are a weird case for this because they don't wrap even the way long words do (i.e. antidisestablishmentarianism).

**Comment by DerekCaelin** [comment]
ok

**Comment by shrouxm** [comment]
this issue also occurs in the landscapes view when clicking on a landscape marker whose landscape's name contains a very long word. this should also be fixed by the above PR
