### ISSUE TITLE
Upload landscape boundaries with common mapping file formats

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#560]
Terraso requires the user to provide a .json or .geojson file in order to demonstrate the bounds of the landscape. However, a common file format (especially among Esri users) is the Shapefile. Other popular file formats are .KML and .KMZ. Users who have a shapefile must find a way to convert it to a geojson file in order to upload to Terraso.

How might we make it easier for users who have alternative file formats to upload it to Terraso?

- [Spec](https://docs.google.com/document/d/17FaE9kqlv04ZksbRozRNiBafmwI82HXs9i5GW7LRLKY/edit)

**Comment by shrouxm** [comment]
@DerekCaelin closing because i now see all the listed formats as an option for map boundary file upload, lmk if it's still relevant!
