### ISSUE TITLE
Plausible Update: record landscape name

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#613]
![image](https://user-images.githubusercontent.com/10799815/203588836-d5bb42a1-f375-4a8e-8142-4092efcc5101.png)

## Description
Please record the name of the landscape in the "landscape creation" plausible event.

**Comment by david-code** [comment]
It looks like the commit `[1034ad5](https://github.com/techmatters/terraso-web-client/commit/1034ad5a10a3a33ce08a3654ad3d600e85c2de20)` Jose made should change this. The next time a user creates a landscape on production this information should be available.
