### ISSUE TITLE
ILM Guide has inconsistent padding depending on the size of the window

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#615]
![padding](https://user-images.githubusercontent.com/10799815/203624082-0266aa7f-5348-4102-81f4-45cb52ce7057.gif)

## Description
Between the widths of 769 and 1160, the space between text and window edge is 0.

## Steps To Reproduce
- open https://terraso.org/ilm
- resize window

## Expected behavior
consistent minimum spacing

## Additional context
Brave Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by paulschreiber** [comment]
What is the desired minimum spacing? @shivaniSri11 @Hanal-code

**Comment by paulschreiber** [comment]
Also, this bug should be in terraso-wp-theme, not web-client, since it's not app bug.

**Comment by shivaniSri11** [comment]
3em looks good from my understanding.
