### ISSUE TITLE
Button component rendered as <a> tag

### ISSUE THREAD

**Issue by josebui** [techmatters/terraso-web-client#625]
## Description
When using Button with react router link the html markup shows as a <a> element

## Steps To Reproduce

1. Go to URL: /landscapes
2. Find Add Landscape button
3. Inspect markup

## Expected behavior
Elements that look as buttons should be rendered as a <button> tag

## Actual behavior
Some buttons are rendered as <a> elements

## Additional context

- Will this change break the feature of opening links in new tabs?

**Comment by shrouxm** [comment]
when i follow the steps to reproduce i see that the "Add Landscape" button is currently rendered as an <a> tag, has this been fixed already?

**Comment by shrouxm** [comment]
confirmed with @josebui can close
