### ISSUE TITLE
Allow upload of map files to Shared Files & Links module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#630]
Users have map files they want to share with other users in a landscape or group. But they currently can't upload the file because we limit file types.

## Description
* Allow users to upload file formats .kml, .kmz, .geojson, gpx to shared files module.
* Update the language describing what files can be uploaded.
* Designate an icon to represent the files uploaded.

**Comment by DerekCaelin** [comment]
Error: false positive error

https://user-images.githubusercontent.com/10799815/226915325-68fed5d1-85e5-4644-9fc3-c01f87461960.mov

### Steps to reproduce

1. Go to shared files and links module
2. Upload an archived docx.file 
[file](https://github.com/techmatters/terraso-web-client/files/11040290/archived.docx.file.zip)
3. System rejects (good!)
4. Upload a valid esri file 
[file](https://github.com/techmatters/terraso-web-client/files/11040302/valid.esri.shapfile.zip)
5. System allows upload but repeats the warning from the invalid file
![image](https://user-images.githubusercontent.com/10799815/226916550-b424d666-eee4-45eb-83a8-c0f1a57dade4.png)

**Comment by josebui** [comment]
@DerekCaelin this should be fixed on staging now

**Comment by DerekCaelin** [comment]
Confirmed, this is resolved.
