### ISSUE TITLE
Display landscape profile image as a thumbnail on user's home screen.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#631]
If a landscape profile image has been uploaded, display an image as a thumbnail for the landscape on the user's home screen.

![image](https://user-images.githubusercontent.com/10799815/206518636-38fb4cba-f424-43ec-ab66-352b2e9fd5bb.png)
![image](https://user-images.githubusercontent.com/10799815/206518706-c1d5258c-7bab-4175-831c-4e1c13f73069.png)

## Design 

**[SPEC]** 
- landscape profile photo dimensions:  160px W x 90px H 
- 4px rounded corners

**[Mockup]**
<img width="299" alt="image" src="https://user-images.githubusercontent.com/92342777/234360610-60f2499e-bd12-4e00-bfab-55da452686a0.png">

**Use case: No Landscape photo available** to display on Homepage: 
Then, show the landscape placeholder.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/92342777/234725629-9d269d48-9af2-489b-9a1c-688b0f1a056c.png">

**SVG:** 
![LandscapePhoto-placeholder](https://user-images.githubusercontent.com/92342777/234726944-9826fbad-8e00-41ca-851e-b62c2967d966.svg)

Related: #653 

## User Stories / Acceptance Criteria
**Product**
- [x] As a member of a landscape on the home screen, if my landscape's manager has not uploaded a featured image, I want to see a representative thumbnail
- [ ] As a user, I want to be able to click the thumbnail and go to the landscape page (original behavior)

**Design**
- [ ] feature implemented as designed
- [ ] additional issues...

**QA Testing**
Happy Path
- [x] (Manager) - go to home screen, see thumbnail
- [ ] (Manager) - click thumbnail, go to landscape page
- [ ] (Manager) - manager updates profile image
- [ ] (Manager) - Return to home screen, see updated image

Unhappy path
- [x] (Member) - go to home screen, see thumbnail
- [ ] (Member) - click thumbnail, go to landscape page

**Comment by DerekCaelin** [comment]
@Hanal-code Thank you! what happens if no featured image has been provided?

**Comment by Hanal-code** [comment]
Use case: No Landscape photo available to display on Homepage.
Then, show the landscape placeholder.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/92342777/234725629-9d269d48-9af2-489b-9a1c-688b0f1a056c.png">

Additional interaction for Landscape manager(s): 
Thumbnail is linked to `https://app.staging.terraso.net/landscapes/0106-2023/profile-image/edit`

**Comment by DerekCaelin** [comment]
Confirmed, let's implement this.

**Comment by paulschreiber** [comment]
This has been done and is on staging.

**Comment by DerekCaelin** [comment]
Gah this looks so cool! 

@paulschreiber I think the desired functionality for managers is to click on the thumbnail and go to the profile edit screen. (Members would navigate to the landscape page).
