### ISSUE TITLE
Landscape Profile: Add the conditional question for the livelihoods question

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#634]
## Description
If users select ”Crop farming" and/or "Cattle and livestock farming” in the Livelihoods field, 
DISPLAY the production method field.

## Additional context
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/92342777/207181800-d3036df2-9a8c-4972-b887-bf442bbb8438.png">

**Comment by Hanal-code** [comment]
@josebui  Can you fix this issue? 

1. 'Livelihoods' field should not trigger to display 'Agricultural production method' field when `Industry` was selected. 
2.  Selecting `Cattle and livestock farming` didn't trigger the 'Agricultural production method' 

`Crop farming` and/or `Cattle and livestock farming` are the options that can trigger  'Agricultural production method' field.

**[screenshot of issue 1 above]**
<img width="288" alt="image" src="https://user-images.githubusercontent.com/92342777/208712625-beaf4e38-953a-470b-b580-287f8a021dc1.png">

**Comment by josebui** [comment]
@Hanal-code I pushed the fix to staging

**Comment by Hanal-code** [comment]
the fix has been verified.
