### ISSUE TITLE
Bad link in ILM Practical Guide, section 1.4

### ISSUE THREAD

**Issue by ssfrancis** [techmatters/terraso-web-client#642]
## Description
NOT on this repository -- on the WordPress site...

On page: 
  https://terraso.org/guide/landscape-partnership/partnership-strengthening-strategy/ 
the link labeled "Multi-Stakeholder Collaboration for Systemic Change: A New Approach to Strengthening Farmer Support Systems" is bad.  It goes to:
  https://www.undp.org/content/gcp/en/home/tools/farmer-support-systems  (which seems to 404?)
and it should go to:
  https://www.undp.org/publications/multi-stakeholder-collaboration-systemic-change-new-approach-strengthening-farmer-support-systems

## Additional context
see related feature request for auto-checking for 404 errors

**Comment by paulschreiber** [comment]
Fixed.
