### ISSUE TITLE
change colors on landscape map to increase contrast

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#644]
![image](https://user-images.githubusercontent.com/10799815/208977439-752ad106-306f-46dc-a261-e5df37665298.png)

Landscape color is difficult to distinguish against satellite base map. Suggest changing the color to make it easier to distinguish.

**Comment by paulschreiber** [comment]
@DerekCaelin @Hanal-code What color should we use?

**Comment by Hanal-code** [comment]
@paulschreiber Change the color to `#FF580D`

**MOCKUP**
<img width="788" alt="image" src="https://user-images.githubusercontent.com/92342777/233747189-75b20c8e-c924-4812-8e0d-fdaf43f15906.png">

**Comment by paulschreiber** [comment]
This is on staging:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/86784/233793176-d045fdd9-069f-49b1-9146-639ab7db6504.png">

I find the tex a bit hard to read. What about making it bold like this?
<img width="624" alt="image" src="https://user-images.githubusercontent.com/86784/233793193-81ee9125-960b-4912-b91e-667295c7ddf5.png">

**Comment by paulschreiber** [comment]
@Hanal-code Staging has been updated with 14px black text.
