### ISSUE TITLE
data map creation error in step 1 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#655]
## Steps To Reproduce

1. Be a member of [Rocky Hill Sustainability Team](https://app.terraso.org/groups/rocky-hill-sustainability-team)
2. Go to URL: https://app.terraso.org/groups/rocky-hill-sustainability-team/map/new
3. Select "Rocky Hill..." file to make the data map
4. Select 'Next' 
5. Notice the error message 

## Expected behavior
No error or a better explanation how to resolve it. 
I tried multiple times already. 

## Actual behavior
<img width="910" alt="image" src="https://user-images.githubusercontent.com/92342777/212139032-55e0e348-304b-497d-85d3-0fbf5bec5deb.png">

**Comment by Hanal-code** [comment]
Derek found this XLS file doesn't contain the lat & long columns. 
So he added them and uploaded it again. But still unable to create the map. 
[Slack conversation thread (https://tech-matters.slack.com/archives/C01C1FZANBG/p1673546520484639]

**Comment by DerekCaelin** [comment]
By copying the data in the "Rocky Hill Historic Sites" into a new spreadsheet, uploading that, and proceeding along data mapping, I am able to make a map:

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/10799815/212153014-eb675352-8ded-4fb0-b8f5-944231c12bbd.png">

**Comment by DerekCaelin** [comment]
this appears to be resolved.
