### ISSUE TITLE
Plausible Events Enhancement - Upload Files, Make Map, Create Landscape Boundary

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#672]
Please update the following Plausible events. We want to be able to talk about Terraso events in relation to ILM Outputs. 

Upload File 
- Tag: `ILM Output`: `Results and analysis of impact`
- Link to File

Make Map
- Tag: `ILM Output`: `Results and analysis of impact`
- Link to published map

Create landscape boundary:
- Tag: `ILM Output` : `Map of the landscape boundaries`

**Comment by josebui** [comment]
@DerekCaelin I have some questions:

`Upload File`
- Is this related to uploding media in story maps? or is this related to the shared data module?
- If this is related also to media files, should we trigger the even when the user selects a file? or after the user click save draft or publish?

`Make Map`
- Will this one only be triggered after the user publishes the story map?

`Create landscape boundary`
- What are the parameters we want to track with this one?

**Comment by DerekCaelin** [comment]
> Is this related to uploding media in story maps? or is this related to the shared data module?
Shared data module, please

> If this is related also to media files, should we trigger the even when the user selects a file? or after the user click save draft or publish?
Not applicable at this time

> Will this one only be triggered after the user publishes the story map?
Yes. 

> Create landscape boundary - What are the parameters we want to track with this one?
The event should trigger when someone creates a landscape boundary by drawing it (either when creating a new landscape or editing a pre-existing landscape).

**Comment by josebui** [comment]
@DerekCaelin Also, can you add the ILM Outputs texts?

**Comment by DerekCaelin** [comment]
> For Upload File there is now static URL referencing the files so we can't send that to plausible

Alternatively, can we send the name of the file and the landscape it was shared with?

(Why can we not send static URLs to plausible?)

> Also, can you add the ILM Outputs texts?

Done!

**Comment by josebui** [comment]
> Alternatively, can we send the name of the file and the landscape it was shared with?
Yes, we should have that data

> (Why can we not send static URLs to plausible?)
It is a good practice to just provide temporary access for this kind of resources, we want to make sure (as much as possible) that only the user with access to this file can download it, and if they share it, it will expire after a fixed time, let me know if that makes sense

**Comment by DerekCaelin** [comment]
Understandable. The interest here is for Terraso team members to be able to review files to understand how users are interacting with the site.  The assumption would be that Terraso team members would only be able to access the files if they were already granted permission. Knowing where the files were uploaded to (group/landscape) should allow us to follow up and request access from the user.

So: knowing where the file upload occurred is enough.

**Comment by DerekCaelin** [comment]
> Make Map: Is this one talking about data maps? beacuse there is another issues for story maps https://github.com/techmatters/terraso-web-client/issues/673

You're right, this was unclear. I am referring to Data Maps in this request.

> Create landscape boundary: Right now there is an existing event when the user creates a landscape through the landscape creation wizard that is called Landscape creation - exit that one already contains some data, should I add the ILM Output to this one? or should I create a separate one? Also this event is just tracking the event when the boundary is added through the create landscape wizard, if you update the boundary later it will not create this event

I would like to tag the ILM output to when draws a boundary, both if they are doing it as a part of creation **and** if they are updating a pre-existing landscape.

Reason: We and our partners want to know if we are impacting people's practice of ILM. If someone draws a polygon (as opposed to dropping a pin or uploading a shapefile) we can reasonably assume that we helped them by giving them a tool to create a digital map of their landscape.
