### ISSUE TITLE
Plausible Event Enhancement - Storymap Published

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#673]
Create event in Plausible (if not included already):

**Storymap Published**
Tags:
- Username
- URL (where can the map be found)
- ILM Output = Landscape Narratives

**Comment by josebui** [comment]
@DerekCaelin As far as I understand we should not add indentifiers for users in plausible, in this case the username

**Comment by DerekCaelin** [comment]
OK - url and ILM output is fine for now.

**Comment by josebui** [comment]
Hey @DerekCaelin can you give me more context on what `ILM Output` is, and how we plan to use it? I need to define how to name the property I am thinking `ilmOutput` and the value I am not sure how to maintain, what I am getting is that each event migth have a different value, or how will that work?

**Comment by DerekCaelin** [comment]
@josebui and I met to discuss this. We agreed to create a separate event to track this action, and to replace the numerical value 4.3 with the string "Landscape Narratives"

**Comment by josebui** [comment]
@DerekCaelin This should be ready on staging

**Comment by DerekCaelin** [comment]
Thank you
