### ISSUE TITLE
Can't link to a youtube video in story map 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#686]
![image](https://user-images.githubusercontent.com/10799815/218495507-bfa6b72b-c025-4eb8-953f-5ad9948a3dee.png)

## Description
When I provide a youtube URL in the media upload section, I get the message `The URL or embedded code you entered is not valid. Please check it and try again.`.

## Steps To Reproduce
1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. create first chapter
3. add media
4. link to `https://youtu.be/vpc2Q-xc7WA`

## Expected behavior
Story Mapping tool accepts YouTube URL and embeds

## Actual behavior
Receive Error message

**Comment by josebui** [comment]
@DerekCaelin This is more complex than suggested expected behavior. There is a specific embed video option in youtube and vimeo so the accepted URL is online the url that comes from that option, accepting any url means readering the complete page on an iframe and we just need the embed video URL. Right now it should accept the embed code or the specific embed url

**Comment by DerekCaelin** [comment]
@josebui I expected to use the YouTube "share" link, but I think there's an issue processing the URL YouTube provides.

![image](https://user-images.githubusercontent.com/10799815/218520226-be907c02-02d1-4137-99d4-4fc96dda1349.png)
![image](https://user-images.githubusercontent.com/10799815/218520304-feb1eb5f-78fe-4c7f-bc15-ae2f170b9ef9.png)

**Comment by josebui** [comment]
@DerekCaelin Share and embed are not the same, share is the complete website and embed is the url for just the video, I think what we want is the user to embed the file, how did you add the videos in the story maps you created directly?

**Comment by DerekCaelin** [comment]
@josebui when I embedded videos I inserted the embed code YouTube provided into the `description` field. The URL I provided for the embed code was the YouTube page where the video lived.

I think the ideal interaction is that the user provides a the URL for a YouTube, which we then use to generate the embeded video. 

If I copy the embed code from the "share" interface in YouTube, it spits out:
`<iframe width="1280" height="720" src="https://www.youtube.com/embed/07yXl6aV-5w" title="Ellie Goulding vs Daft Punk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`

Could we accept a YouTube link, so that...

<iframe width="{width of chapter box}" height="{proportional height}" `src="{user-provided URL}"` title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

**Comment by josebui** [comment]
@DerekCaelin Let me know if you are avilable to jump on a quick call to talk about this, I think that will be easier

**Comment by DerekCaelin** [comment]
Update: @josebui and I met. Jose says for this iteration he designed the form to accept the **embed** code, which Terraso then parses to extract the video file. 

Working off the URL directly is still preferable from a product perspective (more usable for the user, fewer steps to completion) but we can tackle that in a different iteration. I will test against the feature _as written_.

FYI @Hanal-code

**Comment by DerekCaelin** [comment]
@josebui I still encounter the error when using the embed code. 

![image](https://user-images.githubusercontent.com/10799815/218571577-88571883-8bed-4260-9bc5-4ba82951dfbc.png)

**Comment by josebui** [comment]
@DerekCaelin Can you comment here the url if the youtube video you are trying to embed? and also the code that it is giving you. I tested it with: https://www.youtube.com/watch?v=jfKfPfyJRdk

**Comment by DerekCaelin** [comment]
Hi Jose:

URL: `https://www.youtube.com/watch?v=07yXl6aV-5w`

Embed Code: `<iframe width="1280" height="720" src="https://www.youtube.com/embed/07yXl6aV-5w" title="Ellie Goulding vs Daft Punk There's Something About Us Under The Sheets (video)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`

**Comment by josebui** [comment]
@DerekCaelin This should be fixed now

**Comment by DerekCaelin** [comment]
Confirmed - I can embed a YouTube Video now. Thanks!

![Image](https://user-images.githubusercontent.com/10799815/218781314-24b83c37-4d82-4632-a5bb-ae332fc90884.png)
