### ISSUE TITLE
Story map: Media file(image file) gone missing after Save it as a draft 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#687]
## Description
The uploaded image to the chapter 1 was missing when I returned to the Edit mode after saving the title and first chapter content. 
Note: GitHub erred when trying to attach screenshots. 

## Steps To Reproduce

1. Go to URL:https://app.staging.terraso.net
2. Click 'Create New Story Map'
3. Enter Story map view : https://app.staging.terraso.net/tools/story-maps/create 
4. Add a new chapter and enter text for title 
5. Set the map view for chapter 1.
6. Add media file (photo from your computer) for chapter 1 
7. Add text for chapter 1
8. Click 'Save draft'
9. Note the screen changed to Title chapter from chapter 1
10. Click Chapter 1 
11. Notice the image is missing

**Comment by josebui** [comment]
@Hanal-code This should be fixed now

**Comment by Hanal-code** [comment]
Verified the fix
