### ISSUE TITLE
new story map chapter title overrides other chapter titles

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#690]
https://user-images.githubusercontent.com/10799815/218504533-caebec61-a5ad-4b98-a2a9-7b7167073cfd.mp4

## Description
As I type a chapter title, I see all the chapter titles changing

**Comment by josebui** [comment]
@DerekCaelin I can't reproduce this, do you have the steps to reproduce this? are you always seeing this issue?

**Comment by DerekCaelin** [comment]
I was able to reproduce:

1. Create a new story map
2. Create chapter 1
3. Create chapter 2
4. Delete chapter 1
5. Add a new chapter
6. Error will occur

**Comment by josebui** [comment]
@DerekCaelin This should be fixed now

**Comment by DerekCaelin** [comment]
Confirmed, this appears to be resolved. Thank you!
