### ISSUE TITLE
Map pulses slightly when user types in story map text box

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#692]
https://user-images.githubusercontent.com/10799815/218506482-0196b24c-4f8e-4877-8a95-21aa39c6d64b.mp4

When I type words into the `description` of a story map chapter, I notice the map "pulsing" as if it is zooming out and in very slightly. The changes appear to happen in between words, when I hit `space` and begin another word.

**Comment by josebui** [comment]
@DerekCaelin This should be fixed on staging now

**Comment by DerekCaelin** [comment]
Confirmed, thank you!
