### ISSUE TITLE
cursor defaults to subtitle instead of title on story map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#693]
The cursor initially appears in the `subtitle` field rather than the `title` field.

![image](https://user-images.githubusercontent.com/10799815/218528073-19a6aa3d-ffa7-483b-a372-6f674133157f.png)

**Comment by Hanal-code** [comment]
@josebui  when the title hasn't been added, display 'Untitled' at the top bar instead of leaving it blank.

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin This should be fixed now

**Comment by DerekCaelin** [comment]
My issue is resolved, thanks @josebui - I'll make a new issue for @Hanal-code's issue.
