### ISSUE TITLE
header, sidebar, and footer move as user scrolls down

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#694]
https://user-images.githubusercontent.com/10799815/218528684-99d986ea-265b-4f77-902c-0fcad49f3eee.mp4

The header, sidebar, and footer move unexpectedly as the user scrolls down in the story map.

**Comment by josebui** [comment]
@DerekCaelin  what browser and version are you using?

**Comment by DerekCaelin** [comment]
[Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (x86_64)](https://brave.com/latest/)

It looks like the issue is no longer happening... should I close this issue?

**Comment by josebui** [comment]
If you can't repro anymore yes, it looks fine for me in brave, chrome and safari

**Comment by DerekCaelin** [comment]
Always happy to close an issue...
