### ISSUE TITLE
Story map: Add the set background map button to Title chapter 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#701]
## Description
Users want to set a different background map for the title screen-- e.g. a globe. 
The proposed solution: Adding the same Set Background Map function to the title chapter. 

**Mockup:** 
Figma: https://www.figma.com/file/NlYxkRvnW84rGokeGoPXuV/Easier-storymap-creation-V1.0?node-id=451%3A291&t=4cVh5JWNeCOPYL64-1

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin I didn't notice that this was yet not assigned to me, so it is on staging now, let me know if I should revert it

**Comment by DerekCaelin** [comment]
This is working as expected, thank you!
