### ISSUE TITLE
Story map: Change the thumbnail label for the title chapter to "T" 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#703]
## Description
The current thumbnail label for Title chapter is 0. "T" as abbreviation of Title will communicate clearer as the 'title' concept/term was used in the UI.  

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. See the left pane (thumbnails) 

## Expected behavior
"T" as the title chapter label

## Actual behavior
"0" as the title chapter label

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
The fix has been verified.
