### ISSUE TITLE
Story Map: Save map buttons should be placed at top right 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#704]
## Description
The placement of buttons are inconsistent and less discoverable -- the design of Map view screen and other Story map screens placed the CTA buttons at top right. 

## Steps To Reproduce

1. Go to your story map: https://app.staging.terraso.net/tools/story-maps/
2. Pick a chapter and enter the map view: https://app.staging.terraso.net/tools/story-maps/from-big-to-small/edit
3. Note that Save Map View and Cancel buttons are bottom right 

## Expected behavior
<img width="722" alt="image" src="https://user-images.githubusercontent.com/92342777/218789143-7ead1b00-40b7-4d86-948d-727964a58957.png">

## Actual behavior
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/92342777/218789201-73c06150-97b5-4f36-84ce-36df79c56954.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
Thx @jose. The fix has been verified.
