### ISSUE TITLE
Story Mapping returns an error message when I try to save a draft of preview my story. 

### ISSUE THREAD

**Issue by theladymay** [techmatters/terraso-web-client#706]
## Description
When I am working on a story map if I try to save a draft or preview my map I get an error message that says "oops, something went wrong. Try again in a few minutes".  But it never comes back and I have to start again from scratch. 

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps
2.  crate story map
3. 
4. 
5. 

## Expected behavior

I expect to have my draft saved or see a preview of my map so far.

## Actual behavior

I'm getting a white screen with an error message that says  "oops, something went wrong. Try again in a few minutes" and then I'm unable to get my work back and have to start over. 
<img width="1257" alt="Screenshot 2023-02-15 at 10 37 28 AM" src="https://user-images.githubusercontent.com/17261900/219075520-8c073cf8-d999-40a1-be51-e4a7e47dabd1.png">

**Comment by shrouxm** [comment]
@theladymay i am closing this issue as i suspect it is resolved, let me know if not!
