### ISSUE TITLE
Story map: Link media input field -  errs too early, doesn't reset the field after canceling 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#707]
## Description
Link media input field is not working properly. It errs too early. It doesn't reset the field after canceling. 

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. Add a new chapter
3. Click 'Add media'
4. Note the media dialog
5. Select the Link your media file option 
6. Enter 'ww' 
7. Note the inline error 

additional issue of failing to reset the input field
8. click 'Cancel' after seeing the error message
9. Reopen the add media dialog
10. Notice the inline error message and radio button is selected to Link to media option. 

## Expected behavior
The Inline error message doesn't show up until the users stop typing. Showing up too early.
Once it's canceled or closed, the radio button (and the dialog) gets reset   

## Actual behavior
<img width="654" alt="image" src="https://user-images.githubusercontent.com/92342777/219073555-7721a6e2-33b9-4bc1-8989-f60b2476f16e.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
The fix has been verified.
