### ISSUE TITLE
story map: chapter title size is smaller than the media box header 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#708]
## Description
The chapter title size is smaller than the media box header. It deemphasize the importance of chapter title and make the visual hierarchy unclear. 
Increase the font-size and reduce the margin size. 
`font-size: 1.25rem;
margin-top: -0.5rem;`

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. Add a new chapter 
3. Enter the chapter title
4. Notice how the chapter title gets displayed 

## Expected behavior
<img width="401" alt="image" src="https://user-images.githubusercontent.com/92342777/219079516-89fbe52d-a4ff-44d9-ae49-efc650657c09.png">

## Actual behavior
<img width="431" alt="image" src="https://user-images.githubusercontent.com/92342777/219077691-12386de2-7c46-43a9-963a-3cfa5839233b.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
@jose, can you increase the font size a bit more? `font-size: 1.25rem` will make it look like a chapter title.

**Comment by Hanal-code** [comment]
The fix has been verified.
