### ISSUE TITLE
story map: Link the text dialog is missing the primary button 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#709]
## Description
Link the selected text dialog is missing the primary button. Cancel and Add button have the same secondary button style. 

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. Add a chapter 
3. Add text to Description input area
4. Select a sentence and click 'Add link' button
5. Note the  Add link dialog opens
6. Note the button style is not consistent

## Expected behavior
<img width="589" alt="image" src="https://user-images.githubusercontent.com/92342777/219090039-96ae3099-16aa-4582-b53c-701c76a6af7a.png">

## Actual behavior
<img width="902" alt="image" src="https://user-images.githubusercontent.com/92342777/219083938-aa4af4f5-7d66-4354-bb73-44fb218dcaa7.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
The fix has been verified.
