### ISSUE TITLE
Story map: Tools tips for text edit buttons in the rich text field are missing

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#710]
## Description
Story map: Tools tips for text edit buttons in the rich text field are missing

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. Add a chapter
3. Add text to Description input area
4. Mouse over the buttons; Bold | Italic | Link | Unlink 
5. Note no tooltips available

## Expected behavior
Tooltip appears on mouse over:
 Bold | Italic | Link | Unlink 

## Actual behavior
No tooltip

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
@josebui The fix has been verified. Can you tweak it to pop it open closer to the button? 
[Mockup]
<img width="137" alt="image" src="https://user-images.githubusercontent.com/92342777/219495842-08758787-3615-401c-afbc-664217bf0ede.png">

**Comment by josebui** [comment]
@Hanal-code Hana I moved them to be closer to the buttons, the fix is on staging now

**Comment by Hanal-code** [comment]
Thx [@jose](https://github.com/jose). The fix has been verified.
