### ISSUE TITLE
Story Map: Display YouTube video by collecting YouTube URL rather than Embed Code

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#711]
The user should be able to embed a YouTube video by pasting the URL they see on YouTube, rather than seeking out an embed code.

![Image](https://user-images.githubusercontent.com/10799815/219174347-153e1ef4-94ce-4918-84b6-17e5cc0ece11.png)

**Comment by josebui** [comment]
@DerekCaelin This should be fixed on staging now

**Comment by DerekCaelin** [comment]
Amazing! Confirmed, it works!
