### ISSUE TITLE
Story map: draft story map crashes on save

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#712]
https://user-images.githubusercontent.com/10799815/219184215-26724414-8953-46b8-9a77-02b12d57d43c.mov

When trying to access a saved draft story map (https://app.staging.terraso.net/tools/story-maps/warming-seas-are-carving-into-massive-antarctic-glacier-that-could-trigger-sea-level-rise/) from the home screen, the map loads and then quickly crashes.

[Not shown in video] When was on the "create" screen and selected "save draft" I successfully returned to the home screen. A second later, I received the general error.

**Comment by josebui** [comment]
@DerekCaelin is this happening for all your stories? or just one?

**Comment by josebui** [comment]
@DerekCaelin this should be fixed now

**Comment by DerekCaelin** [comment]
This appears to be resolved.
