### ISSUE TITLE
story map: Add media module is missing the label for the attaching a file option

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#713]
## Description 
The option of attaching a (photo/audio/video) file is missing the label. Users have to read the list of file formats to guess file types and exact file extension. 

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. Add a new chapter
3. Click 'Add media'
4. Note the Add media dialog open 
5. Note the first option's radio button is selected, but no label next to it 

## Expected behavior
Radio button label: `Upload a photo or audio file or a short video file`

[Mockup]

**Comment by josebui** [comment]
@Hanal-code How is this one different to #714 ?

**Comment by Hanal-code** [comment]
Dupe of https://github.com/techmatters/terraso-web-client/issues/714
