### ISSUE TITLE
story map: Upload media file option is missing the label for radio button 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#714]
## Description 
The option of attaching a (photo/audio/video) file is missing the label. Users have to read the list of file formats to guess file types and exact file extension. 

## Steps To Reproduce

1. Go to URL: https://app.staging.terraso.net/tools/story-maps/create
2. Add a new chapter
3. Click 'Add media'
4. Note the Add media dialog open 
5. Note the first option's radio button is selected, but no label next to it 

## Expected behavior
Radio button label: `Upload a photo or audio file or a short video file`

[Mockup] 
See Figma file: https://www.figma.com/file/NlYxkRvnW84rGokeGoPXuV/Easier-storymap-creation-V1.0?node-id=201%3A1003&t=0heLREPSIqGfT2XB-1

**Comment by Hanal-code** [comment]
@josebui Got it. Let's change the text to '`Upload a photo or audio file`' then.

**Comment by josebui** [comment]
@Hanal-code Is this better: 


![Image](https://user-images.githubusercontent.com/1316782/219417174-167c4b70-0926-4e7c-ae8a-59d286bd6672.png)

**Comment by Hanal-code** [comment]
@josebui  yes

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
Thx [@jose](https://github.com/jose). The fix has been verified.
