### ISSUE TITLE
Story Map "description" field strips pasted text of hyperlinks

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#715]
https://user-images.githubusercontent.com/10799815/219475604-14284efc-4106-4e2b-abb1-44bee20c6c7c.mov

If I cut and paste text with hyperlinks and past them into the `description` field, that text loses all reference to hyperlinks.

Steps to reproduce:

1. Copy paste from an article that contains URLs
2. Start a chapter in a story map
3. Paste text into `description` field
4. See that there are no hyperlinks in the pasted text

**Comment by josebui** [comment]
@DerekCaelin This should be fixed on staging now

**Comment by DerekCaelin** [comment]
Confirmed! Thank you.
