### ISSUE TITLE
non human readable message when trying to save a story map draft with a duplicate name

### ISSUE THREAD

**Issue by theladymay** [techmatters/terraso-web-client#716]
-->

## Description
When saving a draft of a story map, if that draft has the same name as a different story map and error pops up that is not 

## Steps To Reproduce

1. Go to URL: [(https://app.staging.terraso.net/tools/story-maps)]
2. 
3. 
4. 

## Expected behavior

I'd get a pop up that says "a story map with this name already exists, please choose a different name"

## Actual behavior

non-human readable message
<img width="1680" alt="Screenshot 2023-02-16 at 11 35 59 AM" src="https://user-images.githubusercontent.com/17261900/219488140-1abe1635-0632-4017-ad26-c52d8ac92997.png">

**Comment by paulschreiber** [comment]
Names no longer need to be unique.
