### ISSUE TITLE
User not warned before navigating away from a draft story map that data will be lost

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#726]
https://user-images.githubusercontent.com/10799815/221279070-577fc3e8-7c7e-4083-b811-6c039a7d22f9.mov

When the user closes the tab on a story map, the tab closes immediately, even though the user is losing unsaved work. They should be informed that their information may not be saved if they move away

![image](https://user-images.githubusercontent.com/10799815/221279349-e3629da3-2c03-4111-a022-2e075819af19.png)

Sample language may be:

`This page is asking you to confirm that you want to leave — information you’ve entered may not be saved.`
`Stay on page` `Leave page`

@Hanal-code do agree that a warning message on navigating away is valuable, and what should the language be?

**Comment by paulschreiber** [comment]
This suggested language is pretty bad — the _page_ isn't asking anything.

Here's the current wording, which is much better:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/86784/221284145-aa46ea22-da20-4877-9c01-b65eabb09d02.png">

**Comment by DerekCaelin** [comment]
I'd be fine with this too.

**Comment by Hanal-code** [comment]
Thx for the suggestions @DerekCaelin @paulschreiber.

@josebui  Here's the mock up:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/92342777/221290550-8f789db3-2747-4d97-82c0-243329ad7aab.png">

Copy: Leave Story Map?
You have unsaved changes that will be lost. Select Save Draft before you leave.

**Comment by DerekCaelin** [comment]
Great!

**Comment by paulschreiber** [comment]
>Leave Story Map?
>You have unsaved changes that will be lost if you leave the page.

**Comment by Hanal-code** [comment]
The final decision from the Copy edit meeting:
[DIALOG TITLE] 
Leave Your Story Map?

[BODY COPY]
You have unsaved changes that will be lost if you leave the page. Select _Save Draft_ before you leave.

[CTA BUTTON LABEL]
Leave

[BUTTON LABEL]
Keep Editing

**Comment by josebui** [comment]
@Hanal-code We can’t have (as far as I know) a way of customizing the look and feel of that dialog, that comes from the browser like the one you see in Facebook

**Comment by Hanal-code** [comment]
@josebui Then, let's move forward to with the browser default dialog.

**Comment by DerekCaelin** [comment]
I believe we can edit the language of the modal, just not the appearance.

Derek Caelin
Sustainable Rocky HillConnect with me on ***@***.***)

------- Original Message -------

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin This is fixed on staging now

**Comment by DerekCaelin** [comment]
This works great! Marking as resolved, thank you Jose!
