### ISSUE TITLE
Story Maps: delete story map (draft/published)

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#736]
As a story map maker, I want to delete my published story map that I am not satisfied with, so I can create a new one easily.

**Comment by Hanal-code** [comment]
[Mockup]
HOMEPAGE: 
**Delete function for a published Map:**
<img width="450" alt="image" src="https://user-images.githubusercontent.com/92342777/224843086-8de4db1e-affe-4f41-8d83-830da396f5fd.png">


Click the Delete button in Story map card to view the interaction with the Delete modal 

https://www.figma.com/proto/NlYxkRvnW84rGokeGoPXuV/Easier-storymap-creation-V1.0?page-id=201%3A563&node-id=508%3A303&viewport=2152%2C2329%2C0.5&scaling=min-zoom&starting-point-node-id=508%3A303

**Delete function for a draft Map:**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/92342777/224842669-febc5ddb-d11c-4ee9-8c2b-f7dea7483477.png">
 

PUBLISHED MAP VIEW: 
View the Delete button above the story map  
<img width="293" alt="image" src="https://user-images.githubusercontent.com/92342777/224842378-cc8ff2cb-a6b7-479d-a01d-953d48cc7b93.png">

CONFIRMATION DIALOG
<img width="772" alt="image" src="https://user-images.githubusercontent.com/92342777/224844836-cc8fea5d-e1b8-432a-a63d-9aa3b7edcd47.png">

The final copy for the Delete dialog is TBD. 
Find the final message in the UI copy doc: https://docs.google.com/document/d/1dKbt2wy2BnvaVQ_I0KmVSx-haEs1RwE-82jl-Mrz6I4/edit#heading=h.6y7847l7jxsa

**Comment by DerekCaelin** [comment]
- [ ] Product signoff
 - [ ] As a story map maker, I want to delete my published story map that I am not satisfied with, so I can create a new one easily.
- [ ] QA
- [ ] Design
- [ ] Engineering

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin This whould be fixed on staging now

**Comment by DerekCaelin** [comment]
![Image](https://user-images.githubusercontent.com/10799815/226707436-f0de032e-118f-4544-a19f-27754f658503.png)

![Image](https://user-images.githubusercontent.com/10799815/226707687-2741df97-96a9-4b97-aff9-2b6084c0ddf5.png)



@josebui could you update the strings for the deletion UI?
