### ISSUE TITLE
YouTube video "accepted" but fails to load.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#737]
https://user-images.githubusercontent.com/10799815/221902966-1c85647a-6287-4d83-ba82-f75a3a277cc3.mov

When I upload a YouTube video, the URL is "accepted" but all that loads is a grey screen.

Reproduce:
* Create a story map
* create a chapter
* Add YouTube video, eg `https://youtu.be/eyLCo7_Is-Y`

![image](https://user-images.githubusercontent.com/10799815/221903741-3dade89f-c610-4ee3-802f-0de9cf53e536.png)

**Comment by josebui** [comment]
@DerekCaelin The fix is on staging now
