### ISSUE TITLE
Allow users to edit their published storymaps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#738]
As a user who has published a storymap I should have a method to edit and re-publish my story.

Currently the user does this by appending /edit to the url of the storymap.

**Comment by Hanal-code** [comment]
@josebui @DerekCaelin  Here's the story map status concept summary and the mockups:
https://www.figma.com/file/NlYxkRvnW84rGokeGoPXuV/Easier-storymap-creation-V1.0?node-id=508%3A303&t=60H4SUUD5aissIQg-1

@jose, can we chat when you are ready to work on this?

**Comment by DerekCaelin** [comment]
@Hanal-code I like the "edit" option appearing on the cards. From the figma, I wasn't sure if there is an option to edit from the published map itself?

![Image](https://user-images.githubusercontent.com/10799815/223742247-8db1b030-14ff-4d3b-b8ec-7095703a4ebd.png)

**Comment by Hanal-code** [comment]
@jose Here's the story map status concept summary and the mockups:
https://www.figma.com/file/NlYxkRvnW84rGokeGoPXuV/Easier-storymap-creation-V1.0?node-id=508%3A303&t=60H4SUUD5aissIQg-1

**Comment by Hanal-code** [comment]
@DerekCaelin  That's a good question -- yes, adding another entry point from the published map will work. I will add to the mockup.

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin this should be fixed on staging now

**Comment by DerekCaelin** [comment]
This is resolved! and looks real pretty.
