### ISSUE TITLE
Storymap - Mapbox search bar does not localize to Spanish

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#739]
![Image](https://user-images.githubusercontent.com/10799815/222833188-f019c5df-ad7c-4b92-8b5a-fe847799ed5a.png)

The search bar in "Establecer mapa de fondo" reads "Search" instead of "Buscar".

**Comment by paulschreiber** [comment]
#739 and #740 effectively the same bug: localize Mapbox maps.

**Comment by DerekCaelin** [comment]
Closing this as a duplicate of #740, which is more robust in its description.

**Comment by DerekCaelin** [comment]
Yes... Somehow I forgot I filed a bug?

Sorry about that, will close one.

Derek Caelin
Sustainable Rocky HillConnect with me on ***@***.***)

------- Original Message -------
