### ISSUE TITLE
Storymap: mapbox does not switch to Spanish when user switches to Spanish

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#740]
![image](https://user-images.githubusercontent.com/10799815/223150277-ed710b65-bb22-4f49-901b-d205ab56c7f1.png)

The word for "search" is not yet translated to spanish in mapbox map when the user's language is set to Spanish.

Reproduce:

1. Set language to spanish
2. Create storymap
3. Set location
4. See the search bar in english

**Comment by josebui** [comment]
@DerekCaelin this should be fixed on staging now

**Comment by DerekCaelin** [comment]
Yes, thank you!
