### ISSUE TITLE
Storymapping - update link to help content, remove YouTube reference

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#741]
![Image](https://user-images.githubusercontent.com/10799815/223188208-2d6b534e-003b-47aa-969a-83766722a9d5.png)

Remove reference to YouTube and update link to written content.
English: https://terraso.org/how-to-make-a-story-map/
Spanish: https://terraso.org/es/como-hacer-un-mapa-de-la-historia/

Want to learn how to create a story map? [Read a tutorial.](www.link-to-content.terraso.org)

**Comment by josebui** [comment]
@DerekCaelin this should be fixed on staging now

**Comment by DerekCaelin** [comment]
Confirmed! Thank you!
