### ISSUE TITLE
StoryMaps: false positive invalid URL error message when adding a video

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#747]
## Description
When adding a media file to a Story Map, the `Enter a valid YouTube or Vimeo URL.` error message appears unexpectedly.

## Steps To Reproduce
1. Go to https://app.staging.terraso.net/tools/story-maps/new
2. Click Add New Chapter
3. Click Add Media
4. Click Link to a YouTube or Vimeo Video
5. Click in the URL field
6. Click Upload a photo or audio file

## Expected behavior
No error

## Actual behavior
`Enter a valid YouTube or Vimeo URL.` error appears

**Comment by josebui** [comment]
@paulschreiber  this should be fixed on staging now

**Comment by paulschreiber** [comment]
Confirmed this is fixed.
