### ISSUE TITLE
StoryMaps: focusing on URL field does not update radio button state

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#748]
## Description
When adding a media file to a Story Map, focusing on the URL field does not update the radio button state

## Steps To Reproduce
1. Go to https://app.staging.terraso.net/tools/story-maps/new
2. Click Add New Chapter
3. Click Add Media
4. Click in the URL field

## Expected behavior
`Link to a YouTube or Vimeo video` is checked

## Actual behavior
`Upload a photo or audio file` is checked.

**Comment by josebui** [comment]
@paulschreiber  this should be fixed on staging now

**Comment by paulschreiber** [comment]
Confirmed this is fixed.
