### ISSUE TITLE
Story map: map title duplicate error message appears for the unique title

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#751]
## Description
Story map title duplicate error message appears when the title is unique. 

After seeing the error message, I checked my Story map list on Homepage and found the new one is listed there. Apparently it's saved, but cannot be published. What's the rules for the story map title to be considered unique? 

## Steps To Reproduce

1. Go to https://app.staging.terraso.net/tools/story-maps/new
2. Enter a unique title 
3. click Save Draft
4. Click Publish

## Expected behavior
Proceed to Published map page.

## Actual behavior
The error message appears - _A Story Map with the same title already exists._

**Comment by Hanal-code** [comment]
@josebui  I think the rule should be less strict. How would a user know all other titles before naming their story. Terraso can use a unique identifier and allow users to name story maps whatever they want.

**Comment by josebui** [comment]
@Hanal-code I agree, I mentioned this constraint to you when I started the implementation of the feature. The constraints to think about here are related to the human redable urls, the current URL structure right now is: 

```
https://app.staging.terraso.net/tools/story-maps/valledupar-sitio-propio
https://app.staging.terraso.net/tools/story-maps/[story map title]
```

If you want this uniqueness constraint to change we need to change how the URL is formed, for groups and lanscapes is easier since we have a unique title across the system, so for example for data maps we have this structure:

```
https://app.staging.terraso.net/landscapes/jose-test-profile-1/map/data-map-title
https://app.staging.terraso.net/landscapes/[landscape name]/map/[data map title]
```

But story maps are not related to landscapes or groups so they can only be unique across the system, or we can have non human redable URLs, or use a user identifier in the URL, but we only have email as the user identifier, that I don't think we should use in a url

**Comment by josebui** [comment]
@Hanal-code 

The issue with `https://app.staging.terraso.net/tools/story-maps/[story map title]-000` is that `000` has to be an identifier in our DB, right now our indentifiers look like `123e4567-e89b-12d3-a456-426614174000` so if you want something like that it will be something like this `https://app.staging.terraso.net/tools/story-maps/[story map title]-123e4567-e89b-12d3-a456-426614174000` that I don't think is a human redable URL, but with more effort we could use a simpler identifier, still that identifier generation has to have a logic, what is the logic you see in that `000`? also I think, keeping that structure this seems better `https://app.staging.terraso.net/tools/story-maps/000/[story map title]`


Another potential solution, not tribial to implement, can be to have non human redable urls until it gets published, at that moment the url can use the title of the story map, so it will only be unique across published story maps

**Comment by josebui** [comment]
Also @paulschreiber @DerekCaelin I would like to get your input on this

**Comment by Hanal-code** [comment]
@josebui  Do we have a unique number as user ID? Conceptually the map belongs to the creator only. `000` has no logic, so swapping it with user Id number (if available) would be more logical. 

The second option sounds ok to me as well.

**Comment by josebui** [comment]
@Hanal-code The user DB identifier also looks like this: `123e4567-e89b-12d3-a456-426614174000`, when you say `second option` you mean the uniqueness only after pusblished?

**Comment by Hanal-code** [comment]
@josebui As we are thinking about the Autosave function, creating a story map with DB identifier is necessary, right?

**Comment by josebui** [comment]
@Hanal-code Yes, that is true, if we want auto save we can have contraints I think, so maybe that is more compatible with the only unique when published scenario

**Comment by DerekCaelin** [comment]
I would like to maintain human readability in the sense that a user can look at a URL and know the subject of the story, identify the link to the story they want to tell. Appending a unique ID to the end  (`https://app.staging.terraso.net/tools/story-maps/[story map title]-123e4567-e89b-12d3-a456-426614174000` ) seems to the most scannable. 

@josebui Is there are reason why ` https://app.staging.terraso.net/tools/story-maps/000/[story map title]` seems better to you?

**Comment by shrouxm** [comment]
another problem with not having an ID in the URL is that if the title of the story map changes then all links to the story map break. whereas if we include both ID and title but only route on ID then we can redirect to the current URL if the story map title changes. as far as format goes, we could also do:

`https://app.staging.terraso.net/tools/story-maps/[story map title]/123e4567-e89b-12d3-a456-426614174000`

**Comment by Hanal-code** [comment]
Engineers, what's the good practice to encode/decode the URL to provide human friendly ones? 
`https://app.staging.terraso.net/tools/story-maps/[story map title]-123e4567-e89b-12d3-a456-426614174000` is not comprehensible. What if `https://app.staging.terraso.net/tools/story-maps/[story map title]-[encoded to shorter digits for human]`? Can we do that?

**Comment by shrouxm** [comment]
what kind of human friendliness are we aiming for? it will be a meaningless series of digits in any case so the ID will never be comprehensible. if the goal is that it is easier to manually type out the URL, we could use crockford's base 32 encoding:
`123e4567-e89b-12d3-a456-426614174000`
`28Z4ASZ8KC9D792P89K185T000`
or if we want it as short as possible we could use base64 encoding:
`Ej5FZ-ibEtOkVkJmFBdAAA`

base32 encoding tries to avoid ambiguous letters (so it has zeros but not Os, only uses capital letters, etc)

in context:
```
https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill/123e4567-e89b-12d3-a456-426614174000
https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill/28Z4ASZ8KC9D792P89K185T000
https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill/Ej5FZ-ibEtOkVkJmFBdAAA
```

but there wouldn't be a way to have it be "comprehensible" in the sense of the ID meaning anything to the user. but yeah it would be good to know where the ask for human friendly URLs is coming from so we can know what to optimize for. to me they are all equally comprehensible, & the 2nd option would be the easiest to type manually.

**Comment by DerekCaelin** [comment]
As I see it, the value add for human readable URLs is primarily for the **recipient**, but also for the **creator** to be able to identify the story being told from the link. 

I recently had two articles shared with me that illustrate the point. 
`https://seekingalpha.com/article/4581106-reading-tea-leaves-on-green-bonds-current-headwinds-and-market-outlook`
and 
`https://www.convergence.finance/news-and-events/news/3929YYiPLvRT1RzW9zB51Z/view`

I can guess the content of the first link, but the only thing I know about the second link is the domain and that it is "news". I am more likely to click on a link when I know what it is telling me.

As a creator, I found being able to start typing "damian" in my search bar, and then seeing an autocomplete to the storymap `https://derekcaelin.github.io/CI-Damian/src/index.html` was handy, but that may be less common value add.

@Hanal-code I think we might need to distinguish between "readable" and "reproduceable".

`https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill-journey-to-sustainability-123e4567-e89b-12d3-a456-426614174000` may not be reproduceable, but it is certainly readable. 

I agree neither base32 or base64 is very easy to reproduce but between the two base64 is shorter, and more reproduceable. @Hanal-code do you think base64 id appended to the URL is a good balance between uniqueness and readability?

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin I agree with @shrouxm comment, we could potentially reduce the size of the identifier, but it is needed, about appending it to the title section, like in:

```
https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill-journey-to-sustainability-123e4567-e89b-12d3-a456-426614174000
```

That is not feasible and could lead to unexpected cases because as you can see the delimiter `-` isused inside the indentifier and also inside the title so it will be difficult to indeintify where one starts and the other one finishes, that is why something like this can work better technically:

```
https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill-journey-to-sustainability/123e4567-e89b-12d3-a456-426614174000
https://app.staging.terraso.net/tools/story-maps/123e4567-e89b-12d3-a456-426614174000/sustainable-rocky-hill-journey-to-sustainability
```

Also @shrouxm made a good point about updating the URL, if the urls are usign the title, after the title gets updated all the links to the previous URL will be broken.

I still feel like the unique constraint after publish can be a potential solution, with that one we can block the title from being modified after it was published and also check the uniqueness of it only at that point

**Comment by DerekCaelin** [comment]
Of these, I prefer:
`https://app.staging.terraso.net/tools/story-maps/sustainable-rocky-hill-journey-to-sustainability/123e4567-e89b-12d3-a456-426614174000` as a good compromise between being readable and unique.

> I still feel like the unique constraint after publish can be a potential solution, with that one we can block the title from being modified after it was published and also check the uniqueness of it only at that point

For the MVP, I'm ok with blocking the title from modifying after publish. I think the ideal user experience would be to redirect from an outdated link to the current content, but I expect that would be more complicated. 

@Hanal-code what do you think?

**Comment by DerekCaelin** [comment]
Very good! @josebui please implement this solution with the shortest feasible unique identifier, and lock the url once published.

**Comment by josebui** [comment]
@DerekCaelin @Hanal-code I want to confirm some things before starting:

1. If we add the indentifier to the URL and remove the uniqueness contraint it will be almost imposible (without users interaction) to go back to the human redabel URLs in the future.

2. Having the title in the URL means that every time the user updates the title all the urls shared will be broken, so even with locking the url (also this mean locking the title, not just the url) when the story map is not published the urls will be broken

**Comment by DerekCaelin** [comment]
> If we add the indentifier to the URL and remove the uniqueness contraint it will be almost imposible (without users interaction) to go back to the human redable URLs in the future.
Yes, let's keep the title and unique identifier for now. If we change our policies going forward, I assume we can change the rules for future links and leave past links as they are?

> Having the title in the URL means that every time the user updates the title all the urls shared will be broken, so even with locking the url (also this mean locking the title, not just the url) when the story map is not published the urls will be broken
I think this is OK for now, because this would be rare occurrance. (Ususally if one publishes a story the title is unlikely to change.) Future enhancements could warn the user of the consequences of the title, or redirect the user with a changed URL to navigate to the new URL with the same unique identifier.

**Comment by paulschreiber** [comment]
We are using UUIDs, which are long and cumbersome. We could mediate the problem by using shorter IDs that are only unique to Terraso Story Maps.

In a different app I wrote, I have this ruby code
```ruby
>> rand(2821109907456).to_s(36)
=> "i01xq4a"
```
Python would be 
```python
''.join(random.choices(string.ascii_lowercase + string.digits, k=7))
```

 A seven-digit random ID is going to be easier to type/share/copy/paste.

Something like this:
```
https://app.staging.terraso.net/tools/story-maps/i01xq4a/
```

If we want the maps to be public, having a readable slug will help with SEO:
```
https://app.staging.terraso.net/tools/story-maps/i01xq4a/sustainable-rocky-hill-journey-to-sustainability
```

**Comment by DerekCaelin** [comment]
> If we want the maps to be public, having a readable slug will help with SEO:
`https://app.staging.terraso.net/tools/story-maps/i01xq4a/sustainable-rocky-hill-journey-to-sustainability`

This solution works for me. A short, unique identifier to append to the human readable url title.

**Comment by Hanal-code** [comment]
Agreed.

**Comment by josebui** [comment]
@DerekCaelin we could potentially maintain different urls in the future, so that is a potential solution, no that clean techinically, but ok. Also with Paul's solution this will not be a tribial implementation I have to do some reasearch so this can get to around a couple of days of work in the worst scenario

**Comment by paulschreiber** [comment]
In WordPress, if you change a slug, people linking to you have to update. In practice, this is not a significant problem because people don't change them that often. It's also possible to keep the old slugs around as redirects, but this is not something we need in the initial release.

**Comment by josebui** [comment]
@paulschreiber I think with your suggestion it seems that there should be collission probabilty between identifiers for multiple story maps, but I am thinking that the shortened identifier joined with the url will make this almost imposible to collide, right? what do you think?

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin They fix is on staging now

**Comment by Hanal-code** [comment]
Verified.
