### ISSUE TITLE
Story Map: Save Draft feedback message copy should say '.... saved' not '...created'

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#753]
When  users save the story map, the Snack bar feedback message appears. 
The copy should be tied to the saving action. 

CURRENT: 
[Story map title] story map has been created

EXPECTED: 
[Story map title] story map has been **saved**

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
The fix has been verified.
