### ISSUE TITLE
STORY MAP: Don't display Outline if no chapter title is available on Title chapter

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#755]
## Description
Reserving empty space with pipes looks odd (See the screenshot below) when chapter title is not available. 
Don't display `Outline:   |  | `  when users haven't enter any chapter title.
## Steps To Reproduce

1. https://app.staging.terraso.net/tools/story-maps/new
2. Add a couple of chapters 
3. Go back to Title chapter or Preview the story map
4. Notice the `Outline:   |  | ` on the title chapter 

## Expected behavior

Don't display`Outline:   |  | ` on the title chapter 

## Actual behavior

<img width="288" alt="image" src="https://user-images.githubusercontent.com/92342777/224191273-f2189f2d-b273-4197-939b-41d1e745f354.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now

**Comment by Hanal-code** [comment]
The fix has been verified


![Image](https://user-images.githubusercontent.com/92342777/224457132-e80b92a6-7249-4d3c-9661-eeb51a00139d.png)
