### ISSUE TITLE
Story Maps: don't display the empty chapter title as a bar in map preview

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#756]
## Description
The a chapter was added without any content (a.k.a. empty chapter), it doesn't need to be included in Preview or published. 
Currently the empty chapter shows up as a gray bar in Preview mode ( see the screenshot)

## Steps To Reproduce

1. https://app.staging.terraso.net/tools/story-maps/new
2. Add a couple of chapters 
3. Skip adding any content to the chapter
4. Click Preview
5. Notice the empty chapter shows up as a gray bar

## Expected behavior
No bar in preview

## Actual behavior
<img width="314" alt="image" src="https://user-images.githubusercontent.com/92342777/224192828-e157168a-3fd2-489f-b376-6fb9d36f3645.png">

**Comment by josebui** [comment]
@Hanal-code This whould be fixed on staging now

**Comment by Hanal-code** [comment]
Fix has been verified.
