### ISSUE TITLE
STORY MAP: Published map should start the date info with 'Published on...' 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#757]
## Description
The published story has a different date copy from the story map draft's. Currently both story map status say the same. They should clarify the different state the story map are in.  

## Steps To Reproduce

1. Publish a story map and create a draft (https://app.staging.terraso.net/tools/story-maps/new)
2. Return to homepage: https://app.staging.terraso.net
3. Notice your story map list has the published one and the story map draft. 
4. Notice the date info copy

## Expected behavior
Published Story map's time stamp begins with 'Published on...' instead of 'Edited on...'

## Actual behavior
<img width="455" alt="image" src="https://user-images.githubusercontent.com/92342777/224194433-d4760a42-a036-4de1-834f-d4406547efe4.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now
