### ISSUE TITLE
Update KoBoToolbox Toolbox Card

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#780]
![Image](https://user-images.githubusercontent.com/10799815/225661992-c24ee9be-9556-4c02-a255-62b5cb7cf593.png)

@hana please review these changes

Remove text:
`KoBoToolbox will be integrated into Terraso in 2022. Use Kobo independently for now.`

Replace image:
![Image](https://user-images.githubusercontent.com/10799815/225663164-23b72052-ece0-4e78-bbb5-b4775acc7976.png)
Source: https://support.kobotoolbox.org/_images/enketo1.png

**Comment by Hanal-code** [comment]
@DerekCaelin  re: image swap. 
What's the key message you'd like to convey with the screenshot? The form is too small. Can you make the form bigger?
The first thing the image says that I can use KoBo in desktop and mobile. Hope that's the top message you want to convey. 

With this update, I'd suggest to add another link to the app (2 in the mockup) and update the link labels. 
Regarding the KoBo SSO screen we are working on, the main link under the image will be changed from the marketing site to KoBo app, right? 
The current link to the marketing site can be moved below the text (1 in the mockup)

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/92342777/225701018-39dc8736-c01b-4262-ad5f-1ad5cfc6d72c.png">

**Comment by DerekCaelin** [comment]
> What's the key message you'd like to convey with the screenshot? The form is too small. Can you make the form bigger?

I pulled this from the KoBo support website, so I'm not able to edit the image. Yes, the message I want to convey is that the tool has a form and is available for desktop and mobile, which is a little more information than the current logo provides. 

> With this update, I'd suggest to add another link to the app (2 in the mockup) and update the link labels.

I like it, yes. 

> Regarding the KoBo SSO screen we are working on, the main link under the image will be changed from the marketing site to KoBo app, right?

Great!

**Comment by Hanal-code** [comment]
Update for "1" above: Iink it to: ` https://www.kobotoolbox.org/features/`

Link label:` Learn more about KoBoToolbox features`

**Comment by DerekCaelin** [comment]
This is not yet complete. 

"Description" - should be "Use this tool to"
