### ISSUE TITLE
Story Maps: increase the story map title size

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#796]
**CURRENT**
the visual hierarchy is reversed with subtitle is being larger than the story map title.

![Image](https://user-images.githubusercontent.com/92342777/226760380-8c87050f-7ab9-4805-86ca-2404d06cf632.png)

**EXPECTED** 
The title is larger than the subtitle. 
[mockup] 
Title: `    font-size: 2rem;`
sub-title: `font-weight: 400;`

![Image](https://user-images.githubusercontent.com/92342777/226760568-464112bf-9aaf-471a-8d4b-735dc90100d8.png)

**Comment by DerekCaelin** [comment]
@josebui this issue was marked as completed 5 days ago but I don't currently see it in production. Will it be live soon?

**Comment by DerekCaelin** [comment]
@josebui nevermind! I see the update now.
