### ISSUE TITLE
Story Maps: disallow whitespace-only titles

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#797]
non-human-readable error when user sets title as a series of spaces

### Steps to reproduce

1. Create Story Map
2. Enter spaces in title and subtitle
3. select "save draft"
4. see error: `Failed to execute request. (Code: required) (Field: title) (Model: StoryMap) (Context: This field is required.)`

### expected behavior

Error should read: `Could not save/publish. Please provide a title for your Story Map.`

**Comment by DerekCaelin** [comment]
@Hanal-code please review.

**Comment by paulschreiber** [comment]
@josebui Make sure we are calling trim() on all fields.

**Comment by Hanal-code** [comment]
> @Hanal-code please review.

The error still persists

**Comment by DerekCaelin** [comment]
@Hanal-code is the proposed language right? `Could not save/publish. Please provide a title for your Story Map.
`

**Comment by DerekCaelin** [comment]
Hana and I spoke. Our new proposed language. `Could not publish your story map without a title. Enter a title and try again.`

@paulschreiber copy edit?

**Comment by paulschreiber** [comment]
If you try to save a story without a title, you get this:
```
Failed to execute request. (Code: required) (Field: title) (Model: StoryMap) (Context: This field is required.)
```

* Are we doing any validation right now?
* Are any fields other than story title required?

Perhaps we should show inline errors, like we do for groups and landscapes:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/86784/226998806-6f1e0cf9-dde3-4b96-b438-4c113e0e1678.png">

**Comment by Hanal-code** [comment]
Showing inline error makes sense as users need to track to down to enter the title.
However the tricky thing is how to ensure the title fields are visible (in viewport) when Save Draft or Publish action was triggered and erred. 
Can we bring the title chapter in focus, so users can see the title? 

Another question -- is the story map title required to save it as draft technically? 
If not, I'd suggest to remove the error with Save Draft action. 
That will reduce the error frequency. 
The current app already title the story map as 'Untitled' when user enters the story map editor.

**Comment by Hanal-code** [comment]
@josebui Error message copy
For Save Draft action - the error should be `Could not save your draft without a title. Enter a title and try again.`
For Publish action - `Could not publish your story map without a title. Enter a title and try again.`

**Comment by josebui** [comment]
@Hanal-code @DerekCaelin This should be fixed on staging now

**Comment by DerekCaelin** [comment]
This works! Thank you, clsing.
