### ISSUE TITLE
Story Maps: can't add link without selecting text

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#798]
https://user-images.githubusercontent.com/10799815/226924895-73073f8e-da4d-42c3-a163-1795f7583cc7.mov

User can't create a link without first selecting text.

### Steps to reproduce

1. Create story map
2. Go to text entry field
3. with empty text field, click the `link` icon
4. type in a valid URL

![Image](https://user-images.githubusercontent.com/10799815/226924445-345c3d99-b12c-495c-86fa-204ecd4bfece.png)

5. click "add link"
6. see that no text has been added

### Actual behavior
No text is added:

![Image](https://user-images.githubusercontent.com/10799815/226924025-d5574936-b94f-4db4-9c7b-c7454d4339cb.png)

### Expected behavior
![Image](https://user-images.githubusercontent.com/10799815/226924228-b196fed0-04b8-4a61-9ef2-25fd0f4c5d05.png)
hyperlinked text appears

**Comment by DerekCaelin** [comment]
If it's working as expected, I think an enhancement can wait until the next sprint.

**Comment by paulschreiber** [comment]
@DerekCaelin this works if you click in the text field first and give it focus.

**Comment by josebui** [comment]
@DerekCaelin @Hanal-code This should be fixed on staging now

**Comment by DerekCaelin** [comment]
This is resolved, thank you!
