### ISSUE TITLE
Story Map: Add '(required)' attribute to the title field

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#799]
## Description
The required field indicator is missing for the story map title

## Steps To Reproduce

1. Go to URL:https://app.staging.terraso.net/tools/story-maps/new
2. Notice the story map title field is missing the required field attribute

## Expected behavior
<img width="299" alt="image" src="https://user-images.githubusercontent.com/92342777/227007177-134c746e-75d1-4fa2-9dfb-a5b212e4c096.png">

## Actual behavior
<img width="894" alt="image" src="https://user-images.githubusercontent.com/92342777/227007905-ea05b34f-2fc2-4e12-af6f-196279000702.png">

**Comment by paulschreiber** [comment]
(required) should not be part of the placeholder, as it disappears when the field gets focus.

**Comment by Hanal-code** [comment]
@josebui Another idea is adding the required field label 
Reference: https://mui.com/material-ui/react-text-field/#form-props

[MOCKUP]
<img width="183" alt="image" src="https://user-images.githubusercontent.com/92342777/227047861-457dc999-25e2-4caa-849a-75c3b0c3a5ce.png">

**Comment by josebui** [comment]
@Hanal-code This should be fixed on staging now
