### ISSUE TITLE
Story Maps: Browser tab reads "Terraso Home" instead of Story Maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#801]
![image](https://user-images.githubusercontent.com/10799815/227551325-210eaa4e-b6db-454a-b631-2dfe3b90db27.png)

## Description
When creating a story map, browser tab reads "Terraso Home" instead of "Terraso Story Maps".

## Steps To Reproduce
1. Go to URL: https://app.terraso.org/tools/story-maps/new

## Expected behavior
Tab Reads `Terraso Story Maps`

## Actual behavior
![image](https://user-images.githubusercontent.com/10799815/227551325-210eaa4e-b6db-454a-b631-2dfe3b90db27.png)

**Comment by paulschreiber** [comment]
Are you asking to update the `<title>` tag?

**Comment by DerekCaelin** [comment]
Yes, please.
------- Original Message -------

**Comment by DerekCaelin** [comment]
@Hanal-code do you agree this is the desired behavior?

**Comment by Hanal-code** [comment]
`<title>` tag needs to be updated in multiple places. 

- `<title>New story map | Terraso </title>` for https://app.terraso.org/tools/story-maps/new. 
- `<title> {story map title} | Terraso </title>` when the draft is saved with the user entered title. Follow the current pattern for the landscape page title handling.
-
-  `<title> Story Maps | Terraso </title>` for https://app.terraso.org/tools/story-maps

**Comment by paulschreiber** [comment]
@DerekCaelin Please verify on staging.

**Comment by paulschreiber** [comment]
@DerekCaelin I've added a distinct title for viewing story maps.
