### ISSUE TITLE
Plausible: Track navigation to shared link 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#803]
We track "outbound clicks" in Plausible, but I specifically want to understand whether people are using our "shared files/links" module. 

## Description
Please track, in plausible, when people navigate to a link shared in the "shared files/links" module. 
- Tag by landscape/group

**Comment by paulschreiber** [comment]
@DerekCaelin This is fixed on staging.

**Comment by DerekCaelin** [comment]
This appears not to be resolved yet.

### Steps taken:

1. Share link in landscape file/link sharing module
2. Log in as new user
3. Click link in landscape file/link sharing module
4. check plausible

### Expected outcome
See event "ClickedSharedLink" (or something similar), tagged by landscape/group, name of file

### Actual outcome
No event is registered
<img width="990" alt="image" src="https://user-images.githubusercontent.com/10799815/230665031-85ca7888-bc30-4ec9-9cca-e563ca1e6ef0.png">

**Comment by paulschreiber** [comment]
Your original request was to add additional metadata (i.e. source group/landscape) to the outbound link event. I did that.

Now you are casking for creation of a custom event. I can do that, too, but that's not what you requested previously.

Are you changing the nature of the request?

**Comment by DerekCaelin** [comment]
Apologies if I wasn't clear. yes, I would like a standalone event which tracks outbound clicks specifically from landscapes and groups, as well as the URL.

**Comment by paulschreiber** [comment]
Added a custom `dataEntry.link.clicked` event.
