### ISSUE TITLE
Show my story maps in the Terraso Story Maps main page

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#814]
<img width="300" alt="Screenshot 2023-03-29 at 11 58 44 AM" src="https://user-images.githubusercontent.com/10799815/228598066-41027e15-5fd2-4dfe-b066-9403429a48ea.png">
Reveal my own story maps as well as others in the [story maps tool page](https://app.terraso.org/tools/story-maps).

## Problem
Users have reported "losing" their story maps because they are not visible in the tools page and do not think to find them in the home page. 

## Value Add
Intuitive discovery of draft and published story maps.

```[tasklist]
### Issues
- [x] Design task - Show my story maps in the Terraso Story Maps main page
- [x] Team Reviews design
- [x] Design task - Copy edits Show my story maps in the Terraso Story Maps main page
- [ ] https://github.com/techmatters/terraso-web-client/issues/1036
- [ ] (optional) Design tweaks based on learning
- [ ] Product tests against acceptance criteria
- [ ] QA
- [ ] Usability testing
```

## Design

![Image](https://github.com/techmatters/terraso-web-client/assets/10799815/ba0d9a20-3952-463a-88e9-92a6c43934ca)

[figma ](https://www.figma.com/file/WKsIP3ONTSoTDmJWiw6J1E/Story-map-V1.1---Collaborate?type=design&node-id=922-7458&mode=design&t=36KwivLhrSlGiQf8-0)

## References

Related to https://github.com/techmatters/terraso-product/issues/20

## Product

- [x] As a user, I should be able to find my own story maps in the tools page. 

## Design
- [x] implemented according to design
- [x] copy editing
- [ ] translation to spanish

**QA**

- [ ] Add story map
- [x] Delete story map
- [ ] Draft state
- [ ] Create a million story maps

**Comment by Hanal-code** [comment]
@DerekCaelin  Verified that story maps in (my) Story Maps module are listed in reverse chronological order.  
<img width="350" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/d832d5ff-edf4-465f-84f0-399c66c08a41">

**Comment by Hanal-code** [comment]
@DerekCaelin @jodiezhuu Verified that story maps in Sample story maps module are listed in reverse chronological order as well. Thanks! 

However, the Storymap page layout (grid) doesn't match to the design -- 1) it's narrower than expected. 2) Top row content doesn't align with the second row content. 

Let me know if you need more details. 

<img width="1058" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/5a8c4ef3-2fe6-4f3d-b733-8904244b46cf">

**Comment by Hanal-code** [comment]
@DerekCaelin  What's the decision on the new title, `Story Maps Created by Others` from the current one, `Sample Story Maps: View What Others Created`? 
I'm open to hear more ideas. 
The purpose of message is to communicate these are not curated Story Maps as good examples, they are other people's work. At the moment, there are 28 story maps.

**Comment by Hanal-code** [comment]
@jodiezhuu  Thx for quick turnaround. One more minor tweak -- can you extend the main container by changing the `max-width: 1200px` for the large viewport? Thank you! 

<img width="557" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/d7219c0d-d943-4efc-a585-33fc172fda97">

**Comment by Hanal-code** [comment]
@jodiezhuu  I noticed 2 cards on the top row don't stack up for the tiny viewport like the ones in the second row. Can you make it like the quick mockup below `( #1 in the mockup below)`?   
`#2`The corner radius of the first card needs to be 8px instead of 4px. Can you change it as well?  Thank you!

[Quick mockup]
<img width="375" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/8eb6c761-ee46-48a0-a97d-20b744998886">

**Comment by Hanal-code** [comment]
DECISION: the card order for the less than 600 px  is 1) user's story maps, 2) Create story maps action module 3) Story map samples. 
Rationale: 1) simpler to implement than the Create-card-at-top mockup 2) Creating a story map on mobile is not supported in at the moment.

**Comment by DerekCaelin** [comment]
This is ready for production.
