### ISSUE TITLE
Plausible does not register a new landscape

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#817]
![image](https://user-images.githubusercontent.com/10799815/229009346-43cd2ba2-05cf-4b3b-b4ea-0d8768f6a3c4.png)

## Description
Plausible should register the creation of a new landscape, but several have been created without triggering a plausible event. 

## Steps To Reproduce

1. Add new landscape
2.check plausible
3. see error

## Expected behavior
See:
Plausible Event
Tags: name of landscape, language of user who created

## Actual behavior
Nothing appears

**Comment by paulschreiber** [comment]
Please be more specific than `see error`. What type of error are you seeing? HTTP error? JavaScript error? etc. What is the error text? Error code?

**Comment by paulschreiber** [comment]
I created a landscape (landscapes/new, enter name, description, country, click Add) on staging, and confirmed:
- an event was sent to plausible (`Landscape created`)
- the Landscape created` goal is shown on Plausible
<img width="765" alt="image" src="https://user-images.githubusercontent.com/86784/230653699-df8d5f94-e1fd-4b69-adb1-8c98afb07d58.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/86784/230653771-824aa6c0-df81-40ce-818e-ea1f7ad9db6a.png">

If this is not happening for you, please provide reproducible steps.
