### ISSUE TITLE
Remove the external link icon from Terraso Story Maps link on Tools page 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#821]
## Description
Remove the external link icon from 'Go to Terraso Story Maps' link on Tools page.  This link does't take users to an external site, so shouldn't have the icon or open in a new tab. 

## Steps To Reproduce

1. Go to https://app.terraso.org/tools
2. Note '[Go to Terraso Story Maps](https://app.terraso.org/tools/story-maps)' link with the external link icon

## Expected behavior
- No icon for Story maps link
- Open https://app.terraso.org/tools/story-maps  in the same tab. 

## Actual behavior
<img width="906" alt="image" src="https://user-images.githubusercontent.com/92342777/229247938-ef9c6c84-71dc-4eae-9b16-018e928ad0d2.png">

**Comment by DerekCaelin** [comment]
Perhaps connected with #818

**Comment by paulschreiber** [comment]
@Hanal-code Please verify this fix on staging.

**Comment by Hanal-code** [comment]
@paulschreiber The fix has been verified.
