### ISSUE TITLE
Provide SVG art for Terraso Story Maps

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#822]
## Description
Please provide an SVG version of this image:
![image](https://user-images.githubusercontent.com/86784/229257193-8e87b79d-d7aa-43af-a76e-62e4443dc9c2.png)

**Comment by Hanal-code** [comment]
Terraso graphics are in the process of updating color palette, so this won't be delivered until #653 is complete. This task is also dependent on the Terraso brand architecture decision.
