### ISSUE TITLE
Users receive email notifications for group management

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#824]
## Description

As we develop Terraso, it is more common that a user who is not logged in would benefit to know that something has happened on the platform. Important events include:

## References
- [Product Spec](https://docs.google.com/document/d/1An5ZZUzET4pEeqKCKvedjjS0GpaGQnSAzPwzNr85Cug/edit#)
- [Figma Designs](https://www.figma.com/file/tglQZ2bRRioNzY6PIxxryZ/Off-app-notifications?node-id=62-1004)
- #804 

#### General

- [x] As a group manager of a closed group, I want to receive the email notification about pending membership requests, so I can accept or reject it in a timely manner.
- [x] As a requester, I want to be notified by email that my request has been approved, so that I know to join. 
- [x] A user who receives a HTML email, I want to select a link in the email that will take them to the page with the appropriate actions.
- [x] As a user, I am able to decide whether I want to receive notifications. 
  - [x] Email 
    - [x] Logged in users one-click unsubscribe from all notifications. 
    - [x] Footer with mailing address for CAN-SPAM compliance
    - [x] 3790 El Camino Real #625, Palo Alto, CA 94306
  - [x] In app settings page

Analytics:
- [x] As a PM, I want to know when people have come to Terraso as a result of receiving a notification, so I can judge how effective the value add is and make adjustments.
- [x] https://github.com/techmatters/terraso-web-client/issues/841
  - [x] Opt-IN
  - [x] Opt-OUT

### Design 
- [x] Implementation matches design
   - [x] https://github.com/techmatters/terraso-web-client/issues/839
- [x] Copy Editing
- [x] Translation (Spanish)

# QA

Happy Path Test

**Manager** 
- [x] User A signs up for a closed group
- [x] User B (manager) receives email notification
  - [x] https://github.com/techmatters/terraso-web-client/issues/834
  - [x] https://github.com/techmatters/terraso-backend/issues/396
- [x] User B navigates from email notification to management screen
  - [x] https://github.com/techmatters/terraso-web-client/issues/836 
- [x] User B takes action and user A enters closed group
- [x] User A receives email informing them of status change

**Opt out / opt in**
- [x] User B can unsubscribe from Terraso notifications from app UI
- [x] User B can resubscribe from app UI

## Issues we wont address before push to prod
- [ ] As a new user, I want to provide authorization to receive emails, so I can control my email traffic. 
- [x] https://github.com/techmatters/terraso-web-client/issues/837

**Comment by paulschreiber** [comment]
@DerekCaelin I added the email credentials to staging. Please try again.

**Comment by DerekCaelin** [comment]
I have repeated the test above and still don't get emails as a manager.

**Comment by DerekCaelin** [comment]
@paulschreiber I figured out the issue. I did not opt in to receiving emails and had to turn them on in my settings. Can we change from opt-in to default accept email notifications? 

After opting in I received the following message:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/10799815/229615389-f197c74b-5eb1-4157-b336-47cc3639b4d3.png">

**Comment by paulschreiber** [comment]
@DerekCaelin I've fixed the `full_name` bug.

**Comment by DerekCaelin** [comment]
Verified that this is fixed. Closing issue.

**Comment by DerekCaelin** [comment]
> As a new user, I will provide authorization to receive emails, so I can control my email traffic. 

Behavior right now is that new users go directly to the home screen and do not go to initial settings. This means that they effectively do not "opt-in" but it is enabled by default.

I don't remember the decision to skip the profile screen during initial log-in. Should this be revisited? @Hanal-code @paulschreiber  your thoughts please.

**Comment by Hanal-code** [comment]
@DerekCaelin  The create account screen should have the email notification setting for users to opt out.

**Comment by paulschreiber** [comment]
@DerekCaelin Per your request, new users will default to allowing notifications. Additionally, a migration was created to apply this setting to existing users.

@Hanal-code The create account screen doesn't have any settings and adding them is out of scope for this work. If we wish to revisit the account creation flow, we can do that at another time.

**Comment by Hanal-code** [comment]
@DerekCaelin Can you create the implementation task in Github? 
The updating the notification setting mockup can be found in Figma: https://www.figma.com/file/tglQZ2bRRioNzY6PIxxryZ/Off-app-notifications?node-id=65%3A1386&t=YSOxPZwpIsO0FeQr-1

**Comment by DerekCaelin** [comment]
Closing the loop - there is now an issue for this: https://github.com/techmatters/terraso-web-client/issues/840
