### ISSUE TITLE
Manager who receives email join request should navigate to group member admin 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#836]
https://user-images.githubusercontent.com/10799815/229864837-f0b2f0a5-4c47-4708-bf83-add669827a0e.mov

## Description
Bug: Users who receive an email notifying them there is a user requesting access to their group navigate to the GROUPS page, as opposed to the GROUP MANAGEMENT for the specific group. 

## Steps To Reproduce

1. User: request to join closed group
2. Manager: receive email
3. Manager: Click CTA in email

## Expected behavior
Navigate to the management page where the group request was made:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/10799815/229866132-9a7d10e7-81e2-40da-8d5a-0a05a41228fb.png">

## Actual behavior
Navigated to high level groups page
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/10799815/229866278-51588aac-4bb4-45b9-9775-cc9d29844fff.png">

**Comment by paulschreiber** [comment]
EXPECTED
>Clicking link goes to https://app.staging.terraso.net/groups/test3/members

ACTUAL
>Clicking link goes to https://app.staging.terraso.net/groups/

This has been fixed and staged.

**Comment by DerekCaelin** [comment]
This is completed.
