### ISSUE TITLE
One-click unsubscribe for non-logged-in-users

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#837]
## Description

User who is not logged into Terraso should have a one-click unsubscribe from emails experience.

## Steps to Replicate

1. User: request access to closed group
2. Manage: receive email notification of request
3. (be logged out of Terraso)
4. Click "unsubscribe"
5. See issue

## Actual Behavior
See login screen for terraso. Select authentication method. Log in and see snack bar notification (unsubscribed).

## Expected Behavior
View screen that confirms unsubscribe (no additional clicks).
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10799815/229888008-f77193c5-e8f0-4cfc-a021-4a400b1a8120.png">

**Comment by paulschreiber** [comment]
This is blocked by general public view work: https://github.com/techmatters/terraso-backend/pull/379

**Comment by DerekCaelin** [comment]
@paulschreiber if #379 is addressed, will this issue be resolved, or will additional work be needed?

I am wondering if we can push #824 without #837 and follow up later in the sprint.

**Comment by paulschreiber** [comment]
- I don't think you meant #379, which is related to social share dialogs. :)
- We can deploy email notifications as-is on Monday
- One-click unsubscribe (https://github.com/techmatters/terraso-web-client/issues/837 https://github.com/techmatters/terraso-backend/pull/399) is mostly complete. Once Public View (https://github.com/techmatters/terraso-backend/pull/379  is merged, we can complete that work (and fix the broken tests)

**Comment by DerekCaelin** [comment]
Eep! Yes, I think I meant the _backend_ [#379](https://github.com/techmatters/terraso-backend/pull/379).

OK, let's plan to release #824 without #837 and follow up.

**Comment by paulschreiber** [comment]
@DerekCaelin This is done and staged.

**Comment by DerekCaelin** [comment]
I encounter an error:

`Error unsubscribing from Terraso emails`

**Steps to reproduce** (Chrome: Version 112.0.5615.49 (Official Build) (arm64)

1. non-manager - request to join closed group
2. manager - receive email
3. manager - copy [unsubscribe link](https://app.staging.terraso.net/notifications/unsubscribe/?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3RlcnJhc28ub3JnIiwiaWF0IjoxNjgxMTU5OTQ2LCJzdWIiOiJiN2ZlYTFhYi03Mjc3LTRiNDUtYTMwMS05MTQ5ZmNlZmM4MGEiLCJqdGkiOiJkZGM1MTM2MDQ2YWU0YmRhODExZDg2MDM1OGZiYjM1YyIsImVtYWlsIjoiZGVyZWtAdGVjaG1hdHRlcnMub3JnIn0.ras8R8-UvxnDXn3FYI39gMiE_rEqVQ0mowpXJxfidMaxrMqxSHTBi8Bk1nyEucK15EgxmrDRgdajAjXYEbgyfA) to incognito window
4. See error

**Comment by paulschreiber** [comment]
Here's the error JSON:
```
{"data":{"unsubscribeUser":{"errors":[{"message":"[{\"message\": \"You must be authenticated to perform this operation\", \"code\": \"unauthorized\"}]"}]}}}
```

**Comment by paulschreiber** [comment]
This should be working now. `commons.py` was not correctly deployed to staging.

**Comment by DerekCaelin** [comment]
Confirmed! Please push to prod!
