### ISSUE TITLE
Provide more detail for notification settings language for profile

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#839]
## Description
Update production language to match accepted design

## Expected behavior
`Notify me when:
[  ] a group I manage has pending requests or my request to join a closed group is approved`

Text is BELOW email address.

## Actual behavior
`EMAIL NOTIFICATIONS
Group membership requests`

Text is above email address

**Comment by paulschreiber** [comment]
Above text is not ready for production. Present text is clearer and more precise.

**Comment by DerekCaelin** [comment]
This is not the stage for copy editing. Please implement the design that was approved.

**Comment by DerekCaelin** [comment]
![image](https://user-images.githubusercontent.com/10799815/230996037-2b4bacd1-2d73-43fd-a0ce-87ecd5c19237.png)

```
Notify me when:
[  ] a group I manage has pending requests or my request to join a closed group is approved
```

**Comment by DerekCaelin** [comment]
@paulschreiber `"Notifications"` should read `Email Notifications`, according to the design. Once this is done, @josebui can provide translation.

**Comment by paulschreiber** [comment]
We don't want two levels of headings. Do you want `Email me when` instead of `Notify me when`

**Comment by DerekCaelin** [comment]
That makes sense - @Hanal-code OK?

**Comment by Hanal-code** [comment]
For screen reader, the checkbox label should be clear & complete -- either 
`Email me when a group ...` or `Notify me when a group ...` works. 

`NOTIFY ME WHEN` also sounds odd as heading on Account profile. Other headings are nouns.

**Comment by DerekCaelin** [comment]
Thanks @Hanal-code. @paulschreiber let's go with the design as hana posted above please.
