### ISSUE TITLE
Plausible doesn't register events: subscribe and unsubscribe to email notifications

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#841]
## Description
Plausible doesn't register when users subscribe or unsubscribe to email notifications. Detecting an opt-out event is important for product to understand whether Terraso notifications are perceived as spam. 

## Steps To Reproduce
1. Go to URL: https://app.staging.terraso.net/account/profile
2. Check/Uncheck the settings box that signs a user up for notifications.
3. Save settings
4. Be PM, check plausible

## Expected behavior
See event: Email notification Subscription (tag: opt in, opt out)

## Actual behavior
No event appears in plausible

**Comment by paulschreiber** [comment]
This data is definitely sent to Plausible: I confirmed in the network inspector:
```
curl 'https://plausible.io/api/event' \
  -H 'authority: plausible.io' \
...
  --data-raw '{"n":"Preference","u":"https://app.staging.terraso.net/account/profile","d":"app.staging.terraso.net","r":"https://github.com/techmatters/terraso-web-client/issues/841","w":1100,"h":0,"p":"{\"emailNotifications\":\"false\",\"language\":\"en-US\"}"}' \
  --compressed
```

**Comment by DerekCaelin** [comment]
![image](https://user-images.githubusercontent.com/10799815/230446250-ca46ab03-3091-4bfb-a8e1-586ed02be321.png)

I'm not seeing the event show up in the Plausible UI under "Goals". Should I be looking elsewhere?

**Comment by paulschreiber** [comment]
Added the goal to https://plausible.io/app.terraso.org/settings/goals

**Comment by DerekCaelin** [comment]
Confirmed and thank you.
