### ISSUE TITLE
Non-group members see "No members" when trying he member list of a private group

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#858]
## Description
An error message states that a group has no members, when in fact the user does not have permission to see the members of a group.

Related: https://github.com/techmatters/terraso-web-client/issues/811

## Steps To Reproduce

1. Attempt to view the members page of a private group where you are not a member, eg, `https://app.staging.terraso.net/groups/dereks-closed-group-cool-kids-only/members`

## Expected behavior
Error should be: `Cannot see members. Become a member of this group to see who is in it.`

## Actual behavior
Error reads `No members`

**Comment by paulschreiber** [comment]
Non-members are now redirected to the group's front page. This mirrors the behaviour of /uploads. See also #859 #811 https://github.com/techmatters/terraso-backend/pull/419

This fix is on staging.

**Comment by DerekCaelin** [comment]
Confirmed and thank you! Please send to staging when appropriate.

**Comment by paulschreiber** [comment]
As noted, the fix is on staging.

**Comment by DerekCaelin** [comment]
Apologies, I meant prod. I tested on staging.
