### ISSUE TITLE
Embedded landscape map should provide a link to the landscape profile.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#863]
## Description
https://app.terraso.org/landscapes/map is a live map of landscapes, the user should be able to navigate to the _now public_ landscape profile

## Current behavior
User sees a landscape name and description
![Image](https://user-images.githubusercontent.com/10799815/232869404-bec53dac-51bd-4480-8903-25b0ff2e4d6b.png)

## Desired behavior
User sees name, description. **New: link to landscape profile.**

**Comment by paulschreiber** [comment]
This is intentional. 
- The landscape pages aren't public; the above design will redirect most site visitors to a Terraso login page.
- This mathc the content/design of the existing map, which shows a name and description.

**Comment by DerekCaelin** [comment]
The intention for the card is to drive people to Terraso to learn more. It is OK for them to log in at this stage.

**Comment by paulschreiber** [comment]
- That's a marketing site feature and decision, not a product feature. 
- This is out of scope for the work being done here (which is to match the existing feature).

**Comment by DerekCaelin** [comment]
Revised this issue and we will tackle it next sprint.

**Comment by paulschreiber** [comment]
@DerekCaelin This can be verified on staging.

**Comment by DerekCaelin** [comment]
This looks great. Please push to production.
