### ISSUE TITLE
Estimate effort to migrate remaining API code into Typescript/the API package and decide whether/when to do that.

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-web-client#881]

**Comment by shrouxm** [comment]
my impressions after having finished the first client refactor:
- effort is very high
- benefit _to the web client_ is not fully realized until relatively late in the migration, because JS UI code which calls the TS API code is still not checked, and the benefits of having the API code in TS can to some extent be offset by the false confidence they give. (e.g. JS UI code could still pass a null or undefined into a TS function which isn't expecting it)
- there is no further current benefit to other clients because all needed code has already been migrated
- there is high potential to create bugs that are not currently caught by automated testing

therefore, my recommendation is that any further migration should wait until we have more comprehensive E2E/integration tests, and then be done on a case-by-case basis, in tandem with other feature work, using the following process:
1. **If** TS migration could be helpful for the feature work, migrate relevant code to TS _without_ implementing any new features.
2. Validate and merge that change.
3. Then implement new features by modifying the existing TS code that we are confident in.

**Comment by shrouxm** [comment]
@josebui could you review the above conclusions re strategizing around future usage of TypeScript in the web client? also i think it would be good to document this decision in a more visible place than a closed issue, do you think a small section in the README would make sense?

**Comment by josebui** [comment]
@shrouxm This makes sense to me, if all the relevant code that the mobile client needs have been migrated I don't see an inmediate need to migrate all the existing code to typescript in one go, doing it by feature or once we get more resources makes sense to me.

I think a good place to document this could be the docs folder in the web client: https://github.com/techmatters/terraso-web-client/tree/main/docs
