### ISSUE TITLE
link button in Story Map inserts URL rather than hyperlinking

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#884]
In a story map chapter, the feature inserts a URL rather hyperlinks

## Steps To Reproduce
1. Start a story map
2. Select text to hyperlink
3. Select the "link" button
4. Paste in a URL, eg `https://app.terraso.org/landscapes/rocky-hill`

## Expected behavior
[words](https://app.terraso.org/landscapes/rocky-hill) words words

## Actual behavior
https://app.terraso.org/landscapes/rocky-hill words words words

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/10799815/233380954-2a19f2e0-2ab2-49c1-8df4-fc62f07e44bf.png">

**Comment by josebui** [comment]
Not reproducible

**Comment by DerekCaelin** [comment]
I've encountered the issue again. It is happening in Firefox 112.0.2 (64-bit) on MacOS 13.3.1, but not in Chrome or Brave.
