### ISSUE TITLE
"all landscapes" map should default to satellite basemap rather than basic

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#886]
The map on https://app.terraso.org/landscapes should default to satellite basemap rather than basic basemap.

## Current
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/10799815/234022824-f158ec93-a6c5-4a28-8fa1-610d17865201.png">

## Desired
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/10799815/234022887-4bf1cd19-441a-4909-8eb9-df579c94d0ce.png">

**Comment by DerekCaelin** [comment]
closing as this is included in https://github.com/techmatters/terraso-web-client/issues/653

**Comment by paulschreiber** [comment]
This has been fixed on staging.

**Comment by DerekCaelin** [comment]
Does does not appear to be resolved on staging yet:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/10799815/234367657-be14c063-95ec-4fa5-8b84-bf45ae1b4140.png">

**Comment by DerekCaelin** [comment]
Confirmed, this is fixed on staging.
