### ISSUE TITLE
Helper text for photo description in landscape profile shows code block instead of human readable description

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#887]
## Description
When clicking on the helper text for a profile description the helper text displays some back-end text instead of human readable instructions. 

## Steps To Reproduce

1. Be admin
2. Go to URL:  https://app.terraso.org/landscapes/lari/profile-image/edit
3. Click on helper text button

## Expected behavior
See Human readable text, eg, "a photo description should blah blah blah"

## Actual behavior
See `landscape.orm_profile_image_description_helper_text`

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/10799815/234043818-d62f34ee-3b26-4307-9bda-7f0667d5ff11.png">

**Comment by paulschreiber** [comment]
FYI:: that is not code, it is a localization key.

**Comment by paulschreiber** [comment]
Fixed the spelling of `form_profile_image_description_helper_text`. Please verify on staging.

**Comment by DerekCaelin** [comment]
Confirmed, this is resolved on staging.
