### ISSUE TITLE
in landscape profile featured image disappears after upload

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#901]
## Description
When the user uploads a new featured image to the landscape, the image disappears and the user can not upload a new image

## Steps To Reproduce

1. Be a landscape manager
2. Go to landscape profile and update image
3. See issue

## Expected behavior
Image updates on profile page and on thumbnail homescreen

## Actual behavior
Image can no longer be seen on profile and is missing on home page 
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/10799815/234926554-0b11b7df-1f96-4fcd-8a70-09ee7e5fb809.png">

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/10799815/234926686-83057760-e6a2-4367-925d-acc6a0e4b898.png">

Relevant to https://github.com/techmatters/terraso-web-client/issues/631#event-9116330616

**Comment by paulschreiber** [comment]
The profile image UUID was stored in the database, but no corresponding folder was created in the S3 bucket.

**Comment by paulschreiber** [comment]
This was due to unrelated work on staging breaking file uploads. I have reverted those changes.
