### ISSUE TITLE
Make Design: show more member profile bubbles in landscape page

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#904]
## Description
Despite having more space in the card, there are a limited number of user profile bubbles displayed. 

## Steps To Reproduce
1. Go to a landscape page, eg https://app.staging.terraso.net/landscapes/town-of-rocky-hill 
2. Look at the member list
3. See issue

## Expected behavior
More landscape member bubbles
<img width="594" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/e23c4849-29c9-4a23-8d5b-19193b3fead7">

## Actual behavior
<img width="599" alt="Screenshot 2023-04-28 at 1 56 54 PM" src="https://user-images.githubusercontent.com/10799815/235220071-679a9ef4-9530-4739-bd0b-c6d07ef6b1f0.png">

**Comment by paulschreiber** [comment]
Please specify a number. How many more would you like to show? Will this differ on desktop versus mobile?

**Comment by Hanal-code** [comment]
@DerekCaelin The mockup is added under 'Expected behavior' section.
