### ISSUE TITLE
Story Maps tutorial link to a broken link

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#921]
## Description
On the Story Maps tool page, we link to a tutorial. That tutorial link is broken.

## Steps To Reproduce

1. Go to URL: https://app.terraso.org/tools/story-maps
2. Click on `Read a tutorial`, 
3. See issue

## Expected behavior
The url links to https://terraso.org/help/how-to-make-a-story-map/

## Actual behavior
The url links to https://terraso.org/how-to-make-a-story-map/ and we get a 404
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/10799815/236044985-e7018431-bf4b-49dd-990e-81baf8d0fb70.png">

**Comment by paulschreiber** [comment]
This is fixed on staging.
