### ISSUE TITLE
404 error - 'Terraso story maps' link on Home page 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#953]
## Description
Story map link on home page gives a 404 error. 

## Steps To Reproduce

1. Go to URL: https://app.terraso.org/
2. Click on 'Terraso Story Maps' link: https://app.terraso.org/story-maps
<img width="460" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/9ace7666-5418-4822-9002-1e7fb8647232">

3. Notice the 404 error

## Expected behavior
Go to: https://app.terraso.org/tools/story-maps
## Actual behavior

<img width="600" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/7df50c99-cc2a-4f63-967b-a927c76d362d">

**Comment by paulschreiber** [comment]
I fixed this yesterday but hadn't sent it for review. Done.
